namespace Artemis.Presentacion.Common
{
    partial class EditorEmpleado
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditorEmpleado));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.formBorderStyle = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.lblTitulo = new System.Windows.Forms.Label();
            this.pnlBotones = new System.Windows.Forms.FlowLayoutPanel();
            this.btnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlPrincipal = new System.Windows.Forms.Panel();
            this.pnlUbicacion = new System.Windows.Forms.TableLayoutPanel();
            this.cmbDepartamentos = new System.Windows.Forms.ComboBox();
            this.cmbMunicipios = new System.Windows.Forms.ComboBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.pnlDatosOpcionales = new System.Windows.Forms.TableLayoutPanel();
            this.txtCorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCedula = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDatosOpcionales = new System.Windows.Forms.Label();
            this.pnlInformacion = new System.Windows.Forms.TableLayoutPanel();
            this.txtPrimerNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSegundoNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPrimerApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSegundoApellido = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblIdentificacion = new System.Windows.Forms.Label();
            this.pnlBotones.SuspendLayout();
            this.pnlPrincipal.SuspendLayout();
            this.pnlUbicacion.SuspendLayout();
            this.pnlDatosOpcionales.SuspendLayout();
            this.pnlInformacion.SuspendLayout();
            this.SuspendLayout();
            // 
            // formBorderStyle
            // 
            this.formBorderStyle.ElipseRadius = 15;
            this.formBorderStyle.TargetControl = this;
            // 
            // lblTitulo
            // 
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(776, 44);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Editar Empleado";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlBotones
            // 
            this.pnlBotones.Controls.Add(this.btnGuardar);
            this.pnlBotones.Controls.Add(this.btnLimpiar);
            this.pnlBotones.Controls.Add(this.btnCancelar);
            this.pnlBotones.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlBotones.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.pnlBotones.Location = new System.Drawing.Point(0, 391);
            this.pnlBotones.Name = "pnlBotones";
            this.pnlBotones.Size = new System.Drawing.Size(776, 51);
            this.pnlBotones.TabIndex = 1;
            // 
            // btnGuardar
            // 
            this.btnGuardar.AllowAnimations = true;
            this.btnGuardar.AllowMouseEffects = true;
            this.btnGuardar.AllowToggling = false;
            this.btnGuardar.AnimationSpeed = 200;
            this.btnGuardar.AutoGenerateColors = false;
            this.btnGuardar.AutoRoundBorders = false;
            this.btnGuardar.AutoSizeLeftIcon = true;
            this.btnGuardar.AutoSizeRightIcon = true;
            this.btnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardar.BackgroundImage")));
            this.btnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.ButtonText = "Guardar";
            this.btnGuardar.ButtonTextMarginLeft = 0;
            this.btnGuardar.ColorContrastOnClick = 45;
            this.btnGuardar.ColorContrastOnHover = 45;
            this.btnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnGuardar.CustomizableEdges = borderEdges1;
            this.btnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGuardar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuardar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconLeft = null;
            this.btnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardar.IconMarginLeft = 11;
            this.btnGuardar.IconPadding = 10;
            this.btnGuardar.IconRight = null;
            this.btnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardar.IconSize = 25;
            this.btnGuardar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGuardar.IdleBorderRadius = 0;
            this.btnGuardar.IdleBorderThickness = 0;
            this.btnGuardar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGuardar.IdleIconLeftImage = null;
            this.btnGuardar.IdleIconRightImage = null;
            this.btnGuardar.IndicateFocus = false;
            this.btnGuardar.Location = new System.Drawing.Point(623, 3);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.OnDisabledState.BorderRadius = 15;
            this.btnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnDisabledState.BorderThickness = 1;
            this.btnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.OnDisabledState.IconLeftImage = null;
            this.btnGuardar.OnDisabledState.IconRightImage = null;
            this.btnGuardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.onHoverState.BorderRadius = 15;
            this.btnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.onHoverState.BorderThickness = 1;
            this.btnGuardar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardar.onHoverState.IconLeftImage = null;
            this.btnGuardar.onHoverState.IconRightImage = null;
            this.btnGuardar.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.BorderRadius = 15;
            this.btnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnIdleState.BorderThickness = 1;
            this.btnGuardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.IconLeftImage = null;
            this.btnGuardar.OnIdleState.IconRightImage = null;
            this.btnGuardar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.BorderRadius = 15;
            this.btnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnPressedState.BorderThickness = 1;
            this.btnGuardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.IconLeftImage = null;
            this.btnGuardar.OnPressedState.IconRightImage = null;
            this.btnGuardar.Size = new System.Drawing.Size(150, 39);
            this.btnGuardar.TabIndex = 0;
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardar.TextMarginLeft = 0;
            this.btnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardar.UseDefaultRadiusAndThickness = true;
            this.btnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // btnLimpiar
            // 
            this.btnLimpiar.AllowAnimations = true;
            this.btnLimpiar.AllowMouseEffects = true;
            this.btnLimpiar.AllowToggling = false;
            this.btnLimpiar.AnimationSpeed = 200;
            this.btnLimpiar.AutoGenerateColors = false;
            this.btnLimpiar.AutoRoundBorders = false;
            this.btnLimpiar.AutoSizeLeftIcon = true;
            this.btnLimpiar.AutoSizeRightIcon = true;
            this.btnLimpiar.BackColor = System.Drawing.Color.Transparent;
            this.btnLimpiar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiar.BackgroundImage")));
            this.btnLimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.ButtonText = "Limpiar";
            this.btnLimpiar.ButtonTextMarginLeft = 0;
            this.btnLimpiar.ColorContrastOnClick = 45;
            this.btnLimpiar.ColorContrastOnHover = 45;
            this.btnLimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLimpiar.CustomizableEdges = borderEdges2;
            this.btnLimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLimpiar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLimpiar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLimpiar.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.IconLeft = null;
            this.btnLimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLimpiar.IconMarginLeft = 11;
            this.btnLimpiar.IconPadding = 10;
            this.btnLimpiar.IconRight = null;
            this.btnLimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLimpiar.IconSize = 25;
            this.btnLimpiar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLimpiar.IdleBorderRadius = 0;
            this.btnLimpiar.IdleBorderThickness = 0;
            this.btnLimpiar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLimpiar.IdleIconLeftImage = null;
            this.btnLimpiar.IdleIconRightImage = null;
            this.btnLimpiar.IndicateFocus = false;
            this.btnLimpiar.Location = new System.Drawing.Point(467, 3);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiar.OnDisabledState.BorderRadius = 15;
            this.btnLimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnDisabledState.BorderThickness = 1;
            this.btnLimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiar.OnDisabledState.IconLeftImage = null;
            this.btnLimpiar.OnDisabledState.IconRightImage = null;
            this.btnLimpiar.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnLimpiar.onHoverState.BorderRadius = 15;
            this.btnLimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.onHoverState.BorderThickness = 1;
            this.btnLimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiar.onHoverState.IconLeftImage = null;
            this.btnLimpiar.onHoverState.IconRightImage = null;
            this.btnLimpiar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.OnIdleState.BorderRadius = 15;
            this.btnLimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnIdleState.BorderThickness = 1;
            this.btnLimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLimpiar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.OnIdleState.IconLeftImage = null;
            this.btnLimpiar.OnIdleState.IconRightImage = null;
            this.btnLimpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.OnPressedState.BorderRadius = 15;
            this.btnLimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnPressedState.BorderThickness = 1;
            this.btnLimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnLimpiar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.OnPressedState.IconLeftImage = null;
            this.btnLimpiar.OnPressedState.IconRightImage = null;
            this.btnLimpiar.Size = new System.Drawing.Size(150, 39);
            this.btnLimpiar.TabIndex = 1;
            this.btnLimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLimpiar.TextMarginLeft = 0;
            this.btnLimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLimpiar.UseDefaultRadiusAndThickness = true;
            this.btnLimpiar.Click += new System.EventHandler(this.BtnLimpiar_Click);
            // 
            // btnCancelar
            // 
            this.btnCancelar.AllowAnimations = true;
            this.btnCancelar.AllowMouseEffects = true;
            this.btnCancelar.AllowToggling = false;
            this.btnCancelar.AnimationSpeed = 200;
            this.btnCancelar.AutoGenerateColors = false;
            this.btnCancelar.AutoRoundBorders = false;
            this.btnCancelar.AutoSizeLeftIcon = true;
            this.btnCancelar.AutoSizeRightIcon = true;
            this.btnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancelar.BackgroundImage")));
            this.btnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.ButtonText = "Cancelar";
            this.btnCancelar.ButtonTextMarginLeft = 0;
            this.btnCancelar.ColorContrastOnClick = 45;
            this.btnCancelar.ColorContrastOnHover = 45;
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCancelar.CustomizableEdges = borderEdges3;
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancelar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancelar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.IconLeft = null;
            this.btnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancelar.IconMarginLeft = 11;
            this.btnCancelar.IconPadding = 10;
            this.btnCancelar.IconRight = null;
            this.btnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancelar.IconSize = 25;
            this.btnCancelar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancelar.IdleBorderRadius = 0;
            this.btnCancelar.IdleBorderThickness = 0;
            this.btnCancelar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancelar.IdleIconLeftImage = null;
            this.btnCancelar.IdleIconRightImage = null;
            this.btnCancelar.IndicateFocus = false;
            this.btnCancelar.Location = new System.Drawing.Point(311, 3);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.OnDisabledState.BorderRadius = 15;
            this.btnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnDisabledState.BorderThickness = 1;
            this.btnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.OnDisabledState.IconLeftImage = null;
            this.btnCancelar.OnDisabledState.IconRightImage = null;
            this.btnCancelar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnCancelar.onHoverState.BorderRadius = 15;
            this.btnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.onHoverState.BorderThickness = 1;
            this.btnCancelar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.onHoverState.IconLeftImage = null;
            this.btnCancelar.onHoverState.IconRightImage = null;
            this.btnCancelar.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnCancelar.OnIdleState.BorderRadius = 15;
            this.btnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnIdleState.BorderThickness = 1;
            this.btnCancelar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.OnIdleState.IconLeftImage = null;
            this.btnCancelar.OnIdleState.IconRightImage = null;
            this.btnCancelar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.BorderRadius = 15;
            this.btnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnPressedState.BorderThickness = 1;
            this.btnCancelar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.OnPressedState.IconLeftImage = null;
            this.btnCancelar.OnPressedState.IconRightImage = null;
            this.btnCancelar.Size = new System.Drawing.Size(150, 39);
            this.btnCancelar.TabIndex = 2;
            this.btnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancelar.TextMarginLeft = 0;
            this.btnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancelar.UseDefaultRadiusAndThickness = true;
            this.btnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // pnlPrincipal
            // 
            this.pnlPrincipal.AutoScroll = true;
            this.pnlPrincipal.Controls.Add(this.pnlUbicacion);
            this.pnlPrincipal.Controls.Add(this.lblUbicacion);
            this.pnlPrincipal.Controls.Add(this.pnlDatosOpcionales);
            this.pnlPrincipal.Controls.Add(this.lblDatosOpcionales);
            this.pnlPrincipal.Controls.Add(this.pnlInformacion);
            this.pnlPrincipal.Controls.Add(this.lblIdentificacion);
            this.pnlPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPrincipal.Location = new System.Drawing.Point(0, 44);
            this.pnlPrincipal.Name = "pnlPrincipal";
            this.pnlPrincipal.Size = new System.Drawing.Size(776, 347);
            this.pnlPrincipal.TabIndex = 2;
            // 
            // pnlUbicacion
            // 
            this.pnlUbicacion.ColumnCount = 4;
            this.pnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.100775F));
            this.pnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 96.89922F));
            this.pnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 374F));
            this.pnlUbicacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 17F));
            this.pnlUbicacion.Controls.Add(this.cmbDepartamentos, 1, 0);
            this.pnlUbicacion.Controls.Add(this.cmbMunicipios, 2, 0);
            this.pnlUbicacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlUbicacion.Location = new System.Drawing.Point(0, 277);
            this.pnlUbicacion.Name = "pnlUbicacion";
            this.pnlUbicacion.RowCount = 1;
            this.pnlUbicacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlUbicacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlUbicacion.Size = new System.Drawing.Size(776, 40);
            this.pnlUbicacion.TabIndex = 5;
            // 
            // cmbDepartamentos
            // 
            this.cmbDepartamentos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbDepartamentos.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbDepartamentos.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbDepartamentos.FormattingEnabled = true;
            this.cmbDepartamentos.Location = new System.Drawing.Point(14, 3);
            this.cmbDepartamentos.Name = "cmbDepartamentos";
            this.cmbDepartamentos.Size = new System.Drawing.Size(367, 28);
            this.cmbDepartamentos.TabIndex = 0;
            this.cmbDepartamentos.SelectedIndexChanged += new System.EventHandler(this.CmbDepartamentos_SelectedIndexChanged);
            // 
            // cmbMunicipios
            // 
            this.cmbMunicipios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.cmbMunicipios.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMunicipios.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cmbMunicipios.FormattingEnabled = true;
            this.cmbMunicipios.Location = new System.Drawing.Point(387, 3);
            this.cmbMunicipios.Name = "cmbMunicipios";
            this.cmbMunicipios.Size = new System.Drawing.Size(368, 28);
            this.cmbMunicipios.TabIndex = 1;
            // 
            // lblUbicacion
            // 
            this.lblUbicacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblUbicacion.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblUbicacion.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.lblUbicacion.Location = new System.Drawing.Point(0, 234);
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.Size = new System.Drawing.Size(776, 43);
            this.lblUbicacion.TabIndex = 4;
            this.lblUbicacion.Text = "¿Dónde se ubica?";
            this.lblUbicacion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlDatosOpcionales
            // 
            this.pnlDatosOpcionales.ColumnCount = 4;
            this.pnlDatosOpcionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.608248F));
            this.pnlDatosOpcionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 96.39175F));
            this.pnlDatosOpcionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 373F));
            this.pnlDatosOpcionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.pnlDatosOpcionales.Controls.Add(this.txtCorreo, 1, 0);
            this.pnlDatosOpcionales.Controls.Add(this.txtCedula, 2, 0);
            this.pnlDatosOpcionales.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlDatosOpcionales.Location = new System.Drawing.Point(0, 181);
            this.pnlDatosOpcionales.Name = "pnlDatosOpcionales";
            this.pnlDatosOpcionales.RowCount = 1;
            this.pnlDatosOpcionales.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlDatosOpcionales.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlDatosOpcionales.Size = new System.Drawing.Size(776, 53);
            this.pnlDatosOpcionales.TabIndex = 3;
            // 
            // txtCorreo
            // 
            this.txtCorreo.AcceptsReturn = false;
            this.txtCorreo.AcceptsTab = false;
            this.txtCorreo.AnimationSpeed = 200;
            this.txtCorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCorreo.AutoSizeHeight = true;
            this.txtCorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtCorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCorreo.BackgroundImage")));
            this.txtCorreo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtCorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtCorreo.BorderColorIdle = System.Drawing.Color.White;
            this.txtCorreo.BorderRadius = 15;
            this.txtCorreo.BorderThickness = 1;
            this.txtCorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCorreo.DefaultText = "";
            this.txtCorreo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCorreo.FillColor = System.Drawing.Color.White;
            this.txtCorreo.ForeColor = System.Drawing.Color.Black;
            this.txtCorreo.HideSelection = true;
            this.txtCorreo.IconLeft = null;
            this.txtCorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.IconPadding = 10;
            this.txtCorreo.IconRight = null;
            this.txtCorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreo.Lines = new string[0];
            this.txtCorreo.Location = new System.Drawing.Point(17, 3);
            this.txtCorreo.MaxLength = 32767;
            this.txtCorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCorreo.Modified = false;
            this.txtCorreo.Multiline = false;
            this.txtCorreo.Name = "txtCorreo";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Black;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCorreo.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCorreo.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtCorreo.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCorreo.OnIdleState = stateProperties4;
            this.txtCorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtCorreo.PasswordChar = '\0';
            this.txtCorreo.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCorreo.PlaceholderText = "Correo";
            this.txtCorreo.ReadOnly = false;
            this.txtCorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCorreo.SelectedText = "";
            this.txtCorreo.SelectionLength = 0;
            this.txtCorreo.SelectionStart = 0;
            this.txtCorreo.ShortcutsEnabled = true;
            this.txtCorreo.Size = new System.Drawing.Size(368, 47);
            this.txtCorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCorreo.TabIndex = 0;
            this.txtCorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCorreo.TextMarginBottom = 0;
            this.txtCorreo.TextMarginLeft = 3;
            this.txtCorreo.TextMarginTop = 1;
            this.txtCorreo.TextPlaceholder = "Correo";
            this.txtCorreo.UseSystemPasswordChar = false;
            this.txtCorreo.WordWrap = true;
            // 
            // txtCedula
            // 
            this.txtCedula.AcceptsReturn = false;
            this.txtCedula.AcceptsTab = false;
            this.txtCedula.AnimationSpeed = 200;
            this.txtCedula.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCedula.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCedula.AutoSizeHeight = true;
            this.txtCedula.BackColor = System.Drawing.Color.Transparent;
            this.txtCedula.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCedula.BackgroundImage")));
            this.txtCedula.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCedula.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCedula.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCedula.BorderColorIdle = System.Drawing.Color.White;
            this.txtCedula.BorderRadius = 15;
            this.txtCedula.BorderThickness = 1;
            this.txtCedula.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCedula.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCedula.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCedula.DefaultText = "";
            this.txtCedula.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtCedula.FillColor = System.Drawing.Color.White;
            this.txtCedula.ForeColor = System.Drawing.Color.Black;
            this.txtCedula.HideSelection = true;
            this.txtCedula.IconLeft = null;
            this.txtCedula.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCedula.IconPadding = 10;
            this.txtCedula.IconRight = null;
            this.txtCedula.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCedula.Lines = new string[0];
            this.txtCedula.Location = new System.Drawing.Point(391, 3);
            this.txtCedula.MaxLength = 32767;
            this.txtCedula.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCedula.Modified = false;
            this.txtCedula.Multiline = false;
            this.txtCedula.Name = "txtCedula";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Black;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCedula.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCedula.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtCedula.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCedula.OnIdleState = stateProperties8;
            this.txtCedula.Padding = new System.Windows.Forms.Padding(3);
            this.txtCedula.PasswordChar = '\0';
            this.txtCedula.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtCedula.PlaceholderText = "Cédula";
            this.txtCedula.ReadOnly = false;
            this.txtCedula.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCedula.SelectedText = "";
            this.txtCedula.SelectionLength = 0;
            this.txtCedula.SelectionStart = 0;
            this.txtCedula.ShortcutsEnabled = true;
            this.txtCedula.Size = new System.Drawing.Size(367, 47);
            this.txtCedula.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCedula.TabIndex = 1;
            this.txtCedula.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCedula.TextMarginBottom = 0;
            this.txtCedula.TextMarginLeft = 3;
            this.txtCedula.TextMarginTop = 1;
            this.txtCedula.TextPlaceholder = "Cédula";
            this.txtCedula.UseSystemPasswordChar = false;
            this.txtCedula.WordWrap = true;
            // 
            // lblDatosOpcionales
            // 
            this.lblDatosOpcionales.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblDatosOpcionales.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDatosOpcionales.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.lblDatosOpcionales.Location = new System.Drawing.Point(0, 138);
            this.lblDatosOpcionales.Name = "lblDatosOpcionales";
            this.lblDatosOpcionales.Size = new System.Drawing.Size(776, 43);
            this.lblDatosOpcionales.TabIndex = 2;
            this.lblDatosOpcionales.Text = "Otros datos opcionales";
            this.lblDatosOpcionales.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlInformacion
            // 
            this.pnlInformacion.ColumnCount = 4;
            this.pnlInformacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 3.608248F));
            this.pnlInformacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 96.39175F));
            this.pnlInformacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 373F));
            this.pnlInformacion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.pnlInformacion.Controls.Add(this.txtPrimerNombre, 1, 0);
            this.pnlInformacion.Controls.Add(this.txtSegundoNombre, 2, 0);
            this.pnlInformacion.Controls.Add(this.txtPrimerApellido, 1, 1);
            this.pnlInformacion.Controls.Add(this.txtSegundoApellido, 2, 1);
            this.pnlInformacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlInformacion.Location = new System.Drawing.Point(0, 38);
            this.pnlInformacion.Name = "pnlInformacion";
            this.pnlInformacion.RowCount = 2;
            this.pnlInformacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlInformacion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlInformacion.Size = new System.Drawing.Size(776, 100);
            this.pnlInformacion.TabIndex = 1;
            // 
            // txtPrimerNombre
            // 
            this.txtPrimerNombre.AcceptsReturn = false;
            this.txtPrimerNombre.AcceptsTab = false;
            this.txtPrimerNombre.AnimationSpeed = 200;
            this.txtPrimerNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrimerNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrimerNombre.AutoSizeHeight = true;
            this.txtPrimerNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtPrimerNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrimerNombre.BackgroundImage")));
            this.txtPrimerNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrimerNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerNombre.BorderColorIdle = System.Drawing.Color.White;
            this.txtPrimerNombre.BorderRadius = 15;
            this.txtPrimerNombre.BorderThickness = 1;
            this.txtPrimerNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrimerNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerNombre.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrimerNombre.DefaultText = "";
            this.txtPrimerNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtPrimerNombre.FillColor = System.Drawing.Color.White;
            this.txtPrimerNombre.ForeColor = System.Drawing.Color.Black;
            this.txtPrimerNombre.HideSelection = true;
            this.txtPrimerNombre.IconLeft = null;
            this.txtPrimerNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerNombre.IconPadding = 10;
            this.txtPrimerNombre.IconRight = null;
            this.txtPrimerNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerNombre.Lines = new string[0];
            this.txtPrimerNombre.Location = new System.Drawing.Point(17, 3);
            this.txtPrimerNombre.MaxLength = 32767;
            this.txtPrimerNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrimerNombre.Modified = false;
            this.txtPrimerNombre.Multiline = false;
            this.txtPrimerNombre.Name = "txtPrimerNombre";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Black;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerNombre.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimerNombre.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerNombre.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerNombre.OnIdleState = stateProperties12;
            this.txtPrimerNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrimerNombre.PasswordChar = '\0';
            this.txtPrimerNombre.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerNombre.PlaceholderText = "Primer Nombre";
            this.txtPrimerNombre.ReadOnly = false;
            this.txtPrimerNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrimerNombre.SelectedText = "";
            this.txtPrimerNombre.SelectionLength = 0;
            this.txtPrimerNombre.SelectionStart = 0;
            this.txtPrimerNombre.ShortcutsEnabled = true;
            this.txtPrimerNombre.Size = new System.Drawing.Size(368, 44);
            this.txtPrimerNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrimerNombre.TabIndex = 0;
            this.txtPrimerNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrimerNombre.TextMarginBottom = 0;
            this.txtPrimerNombre.TextMarginLeft = 3;
            this.txtPrimerNombre.TextMarginTop = 1;
            this.txtPrimerNombre.TextPlaceholder = "Primer Nombre";
            this.txtPrimerNombre.UseSystemPasswordChar = false;
            this.txtPrimerNombre.WordWrap = true;
            // 
            // txtSegundoNombre
            // 
            this.txtSegundoNombre.AcceptsReturn = false;
            this.txtSegundoNombre.AcceptsTab = false;
            this.txtSegundoNombre.AnimationSpeed = 200;
            this.txtSegundoNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSegundoNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSegundoNombre.AutoSizeHeight = true;
            this.txtSegundoNombre.BackColor = System.Drawing.Color.Transparent;
            this.txtSegundoNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSegundoNombre.BackgroundImage")));
            this.txtSegundoNombre.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSegundoNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoNombre.BorderColorIdle = System.Drawing.Color.White;
            this.txtSegundoNombre.BorderRadius = 15;
            this.txtSegundoNombre.BorderThickness = 1;
            this.txtSegundoNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSegundoNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoNombre.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSegundoNombre.DefaultText = "";
            this.txtSegundoNombre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtSegundoNombre.FillColor = System.Drawing.Color.White;
            this.txtSegundoNombre.ForeColor = System.Drawing.Color.Black;
            this.txtSegundoNombre.HideSelection = true;
            this.txtSegundoNombre.IconLeft = null;
            this.txtSegundoNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoNombre.IconPadding = 10;
            this.txtSegundoNombre.IconRight = null;
            this.txtSegundoNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoNombre.Lines = new string[0];
            this.txtSegundoNombre.Location = new System.Drawing.Point(391, 3);
            this.txtSegundoNombre.MaxLength = 32767;
            this.txtSegundoNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSegundoNombre.Modified = false;
            this.txtSegundoNombre.Multiline = false;
            this.txtSegundoNombre.Name = "txtSegundoNombre";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Black;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoNombre.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundoNombre.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoNombre.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoNombre.OnIdleState = stateProperties16;
            this.txtSegundoNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtSegundoNombre.PasswordChar = '\0';
            this.txtSegundoNombre.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoNombre.PlaceholderText = "Segundo Nombre";
            this.txtSegundoNombre.ReadOnly = false;
            this.txtSegundoNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSegundoNombre.SelectedText = "";
            this.txtSegundoNombre.SelectionLength = 0;
            this.txtSegundoNombre.SelectionStart = 0;
            this.txtSegundoNombre.ShortcutsEnabled = true;
            this.txtSegundoNombre.Size = new System.Drawing.Size(367, 44);
            this.txtSegundoNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSegundoNombre.TabIndex = 1;
            this.txtSegundoNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSegundoNombre.TextMarginBottom = 0;
            this.txtSegundoNombre.TextMarginLeft = 3;
            this.txtSegundoNombre.TextMarginTop = 1;
            this.txtSegundoNombre.TextPlaceholder = "Segundo Nombre";
            this.txtSegundoNombre.UseSystemPasswordChar = false;
            this.txtSegundoNombre.WordWrap = true;
            // 
            // txtPrimerApellido
            // 
            this.txtPrimerApellido.AcceptsReturn = false;
            this.txtPrimerApellido.AcceptsTab = false;
            this.txtPrimerApellido.AnimationSpeed = 200;
            this.txtPrimerApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrimerApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrimerApellido.AutoSizeHeight = true;
            this.txtPrimerApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtPrimerApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrimerApellido.BackgroundImage")));
            this.txtPrimerApellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrimerApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerApellido.BorderColorIdle = System.Drawing.Color.White;
            this.txtPrimerApellido.BorderRadius = 15;
            this.txtPrimerApellido.BorderThickness = 1;
            this.txtPrimerApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrimerApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerApellido.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrimerApellido.DefaultText = "";
            this.txtPrimerApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtPrimerApellido.FillColor = System.Drawing.Color.White;
            this.txtPrimerApellido.ForeColor = System.Drawing.Color.Black;
            this.txtPrimerApellido.HideSelection = true;
            this.txtPrimerApellido.IconLeft = null;
            this.txtPrimerApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerApellido.IconPadding = 10;
            this.txtPrimerApellido.IconRight = null;
            this.txtPrimerApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrimerApellido.Lines = new string[0];
            this.txtPrimerApellido.Location = new System.Drawing.Point(17, 53);
            this.txtPrimerApellido.MaxLength = 32767;
            this.txtPrimerApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrimerApellido.Modified = false;
            this.txtPrimerApellido.Multiline = false;
            this.txtPrimerApellido.Name = "txtPrimerApellido";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Black;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerApellido.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrimerApellido.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtPrimerApellido.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerApellido.OnIdleState = stateProperties20;
            this.txtPrimerApellido.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrimerApellido.PasswordChar = '\0';
            this.txtPrimerApellido.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtPrimerApellido.PlaceholderText = "Primer Apellido";
            this.txtPrimerApellido.ReadOnly = false;
            this.txtPrimerApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrimerApellido.SelectedText = "";
            this.txtPrimerApellido.SelectionLength = 0;
            this.txtPrimerApellido.SelectionStart = 0;
            this.txtPrimerApellido.ShortcutsEnabled = true;
            this.txtPrimerApellido.Size = new System.Drawing.Size(368, 44);
            this.txtPrimerApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrimerApellido.TabIndex = 2;
            this.txtPrimerApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrimerApellido.TextMarginBottom = 0;
            this.txtPrimerApellido.TextMarginLeft = 3;
            this.txtPrimerApellido.TextMarginTop = 1;
            this.txtPrimerApellido.TextPlaceholder = "Primer Apellido";
            this.txtPrimerApellido.UseSystemPasswordChar = false;
            this.txtPrimerApellido.WordWrap = true;
            // 
            // txtSegundoApellido
            // 
            this.txtSegundoApellido.AcceptsReturn = false;
            this.txtSegundoApellido.AcceptsTab = false;
            this.txtSegundoApellido.AnimationSpeed = 200;
            this.txtSegundoApellido.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSegundoApellido.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSegundoApellido.AutoSizeHeight = true;
            this.txtSegundoApellido.BackColor = System.Drawing.Color.Transparent;
            this.txtSegundoApellido.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSegundoApellido.BackgroundImage")));
            this.txtSegundoApellido.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoApellido.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSegundoApellido.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoApellido.BorderColorIdle = System.Drawing.Color.White;
            this.txtSegundoApellido.BorderRadius = 15;
            this.txtSegundoApellido.BorderThickness = 1;
            this.txtSegundoApellido.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSegundoApellido.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoApellido.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSegundoApellido.DefaultText = "";
            this.txtSegundoApellido.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtSegundoApellido.FillColor = System.Drawing.Color.White;
            this.txtSegundoApellido.ForeColor = System.Drawing.Color.Black;
            this.txtSegundoApellido.HideSelection = true;
            this.txtSegundoApellido.IconLeft = null;
            this.txtSegundoApellido.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoApellido.IconPadding = 10;
            this.txtSegundoApellido.IconRight = null;
            this.txtSegundoApellido.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSegundoApellido.Lines = new string[0];
            this.txtSegundoApellido.Location = new System.Drawing.Point(391, 53);
            this.txtSegundoApellido.MaxLength = 32767;
            this.txtSegundoApellido.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSegundoApellido.Modified = false;
            this.txtSegundoApellido.Multiline = false;
            this.txtSegundoApellido.Name = "txtSegundoApellido";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties21.FillColor = System.Drawing.Color.White;
            stateProperties21.ForeColor = System.Drawing.Color.Black;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoApellido.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSegundoApellido.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties23.FillColor = System.Drawing.Color.White;
            stateProperties23.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtSegundoApellido.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoApellido.OnIdleState = stateProperties24;
            this.txtSegundoApellido.Padding = new System.Windows.Forms.Padding(3);
            this.txtSegundoApellido.PasswordChar = '\0';
            this.txtSegundoApellido.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtSegundoApellido.PlaceholderText = "Segundo Apellido";
            this.txtSegundoApellido.ReadOnly = false;
            this.txtSegundoApellido.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSegundoApellido.SelectedText = "";
            this.txtSegundoApellido.SelectionLength = 0;
            this.txtSegundoApellido.SelectionStart = 0;
            this.txtSegundoApellido.ShortcutsEnabled = true;
            this.txtSegundoApellido.Size = new System.Drawing.Size(367, 44);
            this.txtSegundoApellido.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSegundoApellido.TabIndex = 3;
            this.txtSegundoApellido.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSegundoApellido.TextMarginBottom = 0;
            this.txtSegundoApellido.TextMarginLeft = 3;
            this.txtSegundoApellido.TextMarginTop = 1;
            this.txtSegundoApellido.TextPlaceholder = "Segundo Apellido";
            this.txtSegundoApellido.UseSystemPasswordChar = false;
            this.txtSegundoApellido.WordWrap = true;
            // 
            // lblIdentificacion
            // 
            this.lblIdentificacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblIdentificacion.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblIdentificacion.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.lblIdentificacion.Location = new System.Drawing.Point(0, 0);
            this.lblIdentificacion.Name = "lblIdentificacion";
            this.lblIdentificacion.Size = new System.Drawing.Size(776, 38);
            this.lblIdentificacion.TabIndex = 0;
            this.lblIdentificacion.Text = "¿Cómo lo identificamos?";
            this.lblIdentificacion.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // EditorEmpleado
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(776, 442);
            this.Controls.Add(this.pnlPrincipal);
            this.Controls.Add(this.pnlBotones);
            this.Controls.Add(this.lblTitulo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "EditorEmpleado";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Editor Empleado";
            this.pnlBotones.ResumeLayout(false);
            this.pnlPrincipal.ResumeLayout(false);
            this.pnlUbicacion.ResumeLayout(false);
            this.pnlDatosOpcionales.ResumeLayout(false);
            this.pnlInformacion.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse formBorderStyle;
        private System.Windows.Forms.Panel pnlPrincipal;
        private System.Windows.Forms.FlowLayoutPanel pnlBotones;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.TableLayoutPanel pnlInformacion;
        private System.Windows.Forms.Label lblIdentificacion;
        private System.Windows.Forms.Label lblDatosOpcionales;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrimerNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtSegundoNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrimerApellido;
        private Bunifu.UI.WinForms.BunifuTextBox txtSegundoApellido;
        private System.Windows.Forms.TableLayoutPanel pnlDatosOpcionales;
        private Bunifu.UI.WinForms.BunifuTextBox txtCorreo;
        private Bunifu.UI.WinForms.BunifuTextBox txtCedula;
        private System.Windows.Forms.TableLayoutPanel pnlUbicacion;
        private System.Windows.Forms.ComboBox cmbDepartamentos;
        private System.Windows.Forms.ComboBox cmbMunicipios;
        private System.Windows.Forms.Label lblUbicacion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLimpiar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancelar;
    }
}