namespace Artemis.Presentacion.Principal
{
    partial class Principal
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Principal));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.paletaDiseños = new ComponentFactory.Krypton.Toolkit.KryptonPalette(this.components);
            this.pnlTop = new System.Windows.Forms.Panel();
            this.pnlSideBar = new System.Windows.Forms.Panel();
            this.btnVentas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUsuarios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProveedores = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnProductos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmpleados = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCompras = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCategorias = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlPrincipal = new System.Windows.Forms.Panel();
            this.pnlSideBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // paletaDiseños
            // 
            this.paletaDiseños.ButtonSpecs.FormClose.Image = global::Artemis.Properties.Resources.mc_red;
            this.paletaDiseños.ButtonSpecs.FormClose.ImageStates.ImageNormal = global::Artemis.Properties.Resources.mc_red;
            this.paletaDiseños.ButtonSpecs.FormClose.ImageStates.ImagePressed = global::Artemis.Properties.Resources.mc_red;
            this.paletaDiseños.ButtonSpecs.FormClose.ImageStates.ImageTracking = global::Artemis.Properties.Resources.mc_red;
            this.paletaDiseños.ButtonSpecs.FormMax.Image = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormMax.ImageStates.ImageNormal = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormMax.ImageStates.ImagePressed = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormMax.ImageStates.ImageTracking = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormMin.Image = global::Artemis.Properties.Resources.mc_green;
            this.paletaDiseños.ButtonSpecs.FormMin.ImageStates.ImageNormal = global::Artemis.Properties.Resources.mc_green;
            this.paletaDiseños.ButtonSpecs.FormMin.ImageStates.ImagePressed = global::Artemis.Properties.Resources.mc_green;
            this.paletaDiseños.ButtonSpecs.FormMin.ImageStates.ImageTracking = global::Artemis.Properties.Resources.mc_green;
            this.paletaDiseños.ButtonSpecs.FormRestore.Image = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormRestore.ImageStates.ImageNormal = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormRestore.ImageStates.ImagePressed = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.ButtonSpecs.FormRestore.ImageStates.ImageTracking = global::Artemis.Properties.Resources.mc_yellw;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Back.Color1 = System.Drawing.Color.Black;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Back.Color2 = System.Drawing.Color.Black;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Back.ColorAngle = 45F;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Back.GraphicsHint = ComponentFactory.Krypton.Toolkit.PaletteGraphicsHint.AntiAlias;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.Color1 = System.Drawing.Color.Black;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.Color2 = System.Drawing.Color.Black;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.ColorAngle = 45F;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.Rounding = 20;
            this.paletaDiseños.FormStyles.FormMain.StateCommon.Border.Width = 1;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Back.Color1 = System.Drawing.Color.Black;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Back.Color2 = System.Drawing.Color.Black;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Back.ColorAngle = 45F;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Back.GraphicsHint = ComponentFactory.Krypton.Toolkit.PaletteGraphicsHint.AntiAlias;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Border.Color1 = System.Drawing.Color.Black;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Border.Color2 = System.Drawing.Color.Black;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Border.ColorAngle = 45F;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Border.DrawBorders = ((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders)((((ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Top | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Bottom) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Left) 
            | ComponentFactory.Krypton.Toolkit.PaletteDrawBorders.Right)));
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.ButtonEdgeInset = 10;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Content.ShortText.Color1 = System.Drawing.Color.White;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Content.ShortText.Color2 = System.Drawing.Color.White;
            this.paletaDiseños.HeaderStyles.HeaderForm.StateCommon.Content.ShortText.ColorAngle = 45F;
            // 
            // pnlTop
            // 
            this.pnlTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlTop.Location = new System.Drawing.Point(0, 0);
            this.pnlTop.Name = "pnlTop";
            this.pnlTop.Size = new System.Drawing.Size(1060, 18);
            this.pnlTop.TabIndex = 0;
            // 
            // pnlSideBar
            // 
            this.pnlSideBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.pnlSideBar.Controls.Add(this.btnVentas);
            this.pnlSideBar.Controls.Add(this.btnUsuarios);
            this.pnlSideBar.Controls.Add(this.btnProveedores);
            this.pnlSideBar.Controls.Add(this.btnProductos);
            this.pnlSideBar.Controls.Add(this.btnEmpleados);
            this.pnlSideBar.Controls.Add(this.btnCompras);
            this.pnlSideBar.Controls.Add(this.btnClientes);
            this.pnlSideBar.Controls.Add(this.btnCategorias);
            this.pnlSideBar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlSideBar.Location = new System.Drawing.Point(0, 18);
            this.pnlSideBar.Name = "pnlSideBar";
            this.pnlSideBar.Size = new System.Drawing.Size(46, 469);
            this.pnlSideBar.TabIndex = 1;
            // 
            // btnVentas
            // 
            this.btnVentas.AllowAnimations = true;
            this.btnVentas.AllowMouseEffects = true;
            this.btnVentas.AllowToggling = false;
            this.btnVentas.AnimationSpeed = 200;
            this.btnVentas.AutoGenerateColors = false;
            this.btnVentas.AutoRoundBorders = false;
            this.btnVentas.AutoSizeLeftIcon = true;
            this.btnVentas.AutoSizeRightIcon = true;
            this.btnVentas.BackColor = System.Drawing.Color.Transparent;
            this.btnVentas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnVentas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVentas.BackgroundImage")));
            this.btnVentas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVentas.ButtonText = "";
            this.btnVentas.ButtonTextMarginLeft = 0;
            this.btnVentas.ColorContrastOnClick = 45;
            this.btnVentas.ColorContrastOnHover = 45;
            this.btnVentas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnVentas.CustomizableEdges = borderEdges1;
            this.btnVentas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVentas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVentas.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnVentas.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnVentas.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnVentas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVentas.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVentas.ForeColor = System.Drawing.Color.White;
            this.btnVentas.IconLeft = global::Artemis.Properties.Resources.ventas;
            this.btnVentas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVentas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVentas.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVentas.IconMarginLeft = 11;
            this.btnVentas.IconPadding = 10;
            this.btnVentas.IconRight = null;
            this.btnVentas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVentas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVentas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVentas.IconSize = 25;
            this.btnVentas.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnVentas.IdleBorderRadius = 0;
            this.btnVentas.IdleBorderThickness = 0;
            this.btnVentas.IdleFillColor = System.Drawing.Color.Empty;
            this.btnVentas.IdleIconLeftImage = global::Artemis.Properties.Resources.ventas;
            this.btnVentas.IdleIconRightImage = null;
            this.btnVentas.IndicateFocus = false;
            this.btnVentas.Location = new System.Drawing.Point(0, 273);
            this.btnVentas.Name = "btnVentas";
            this.btnVentas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVentas.OnDisabledState.BorderRadius = 5;
            this.btnVentas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVentas.OnDisabledState.BorderThickness = 1;
            this.btnVentas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVentas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVentas.OnDisabledState.IconLeftImage = null;
            this.btnVentas.OnDisabledState.IconRightImage = null;
            this.btnVentas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnVentas.onHoverState.BorderRadius = 5;
            this.btnVentas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVentas.onHoverState.BorderThickness = 1;
            this.btnVentas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnVentas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.onHoverState.IconLeftImage = null;
            this.btnVentas.onHoverState.IconRightImage = null;
            this.btnVentas.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnVentas.OnIdleState.BorderRadius = 5;
            this.btnVentas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVentas.OnIdleState.BorderThickness = 1;
            this.btnVentas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnVentas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.ventas;
            this.btnVentas.OnIdleState.IconRightImage = null;
            this.btnVentas.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnVentas.OnPressedState.BorderRadius = 5;
            this.btnVentas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVentas.OnPressedState.BorderThickness = 1;
            this.btnVentas.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnVentas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.OnPressedState.IconLeftImage = null;
            this.btnVentas.OnPressedState.IconRightImage = null;
            this.btnVentas.Size = new System.Drawing.Size(46, 39);
            this.btnVentas.TabIndex = 7;
            this.btnVentas.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVentas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVentas.TextMarginLeft = 0;
            this.btnVentas.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVentas.UseDefaultRadiusAndThickness = true;
            // 
            // btnUsuarios
            // 
            this.btnUsuarios.AllowAnimations = true;
            this.btnUsuarios.AllowMouseEffects = true;
            this.btnUsuarios.AllowToggling = false;
            this.btnUsuarios.AnimationSpeed = 200;
            this.btnUsuarios.AutoGenerateColors = false;
            this.btnUsuarios.AutoRoundBorders = false;
            this.btnUsuarios.AutoSizeLeftIcon = true;
            this.btnUsuarios.AutoSizeRightIcon = true;
            this.btnUsuarios.BackColor = System.Drawing.Color.Transparent;
            this.btnUsuarios.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnUsuarios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUsuarios.BackgroundImage")));
            this.btnUsuarios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsuarios.ButtonText = "";
            this.btnUsuarios.ButtonTextMarginLeft = 0;
            this.btnUsuarios.ColorContrastOnClick = 45;
            this.btnUsuarios.ColorContrastOnHover = 45;
            this.btnUsuarios.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnUsuarios.CustomizableEdges = borderEdges2;
            this.btnUsuarios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUsuarios.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuarios.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnUsuarios.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnUsuarios.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnUsuarios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUsuarios.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsuarios.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.IconLeft = global::Artemis.Properties.Resources.user;
            this.btnUsuarios.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsuarios.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuarios.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUsuarios.IconMarginLeft = 11;
            this.btnUsuarios.IconPadding = 10;
            this.btnUsuarios.IconRight = null;
            this.btnUsuarios.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsuarios.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuarios.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUsuarios.IconSize = 25;
            this.btnUsuarios.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnUsuarios.IdleBorderRadius = 0;
            this.btnUsuarios.IdleBorderThickness = 0;
            this.btnUsuarios.IdleFillColor = System.Drawing.Color.Empty;
            this.btnUsuarios.IdleIconLeftImage = global::Artemis.Properties.Resources.user;
            this.btnUsuarios.IdleIconRightImage = null;
            this.btnUsuarios.IndicateFocus = false;
            this.btnUsuarios.Location = new System.Drawing.Point(0, 234);
            this.btnUsuarios.Name = "btnUsuarios";
            this.btnUsuarios.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuarios.OnDisabledState.BorderRadius = 5;
            this.btnUsuarios.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsuarios.OnDisabledState.BorderThickness = 1;
            this.btnUsuarios.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsuarios.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsuarios.OnDisabledState.IconLeftImage = null;
            this.btnUsuarios.OnDisabledState.IconRightImage = null;
            this.btnUsuarios.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnUsuarios.onHoverState.BorderRadius = 5;
            this.btnUsuarios.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsuarios.onHoverState.BorderThickness = 1;
            this.btnUsuarios.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnUsuarios.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.onHoverState.IconLeftImage = null;
            this.btnUsuarios.onHoverState.IconRightImage = null;
            this.btnUsuarios.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnUsuarios.OnIdleState.BorderRadius = 5;
            this.btnUsuarios.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsuarios.OnIdleState.BorderThickness = 1;
            this.btnUsuarios.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnUsuarios.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.user;
            this.btnUsuarios.OnIdleState.IconRightImage = null;
            this.btnUsuarios.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnUsuarios.OnPressedState.BorderRadius = 5;
            this.btnUsuarios.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUsuarios.OnPressedState.BorderThickness = 1;
            this.btnUsuarios.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnUsuarios.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.OnPressedState.IconLeftImage = null;
            this.btnUsuarios.OnPressedState.IconRightImage = null;
            this.btnUsuarios.Size = new System.Drawing.Size(46, 39);
            this.btnUsuarios.TabIndex = 6;
            this.btnUsuarios.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUsuarios.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUsuarios.TextMarginLeft = 0;
            this.btnUsuarios.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUsuarios.UseDefaultRadiusAndThickness = true;
            // 
            // btnProveedores
            // 
            this.btnProveedores.AllowAnimations = true;
            this.btnProveedores.AllowMouseEffects = true;
            this.btnProveedores.AllowToggling = false;
            this.btnProveedores.AnimationSpeed = 200;
            this.btnProveedores.AutoGenerateColors = false;
            this.btnProveedores.AutoRoundBorders = false;
            this.btnProveedores.AutoSizeLeftIcon = true;
            this.btnProveedores.AutoSizeRightIcon = true;
            this.btnProveedores.BackColor = System.Drawing.Color.Transparent;
            this.btnProveedores.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProveedores.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProveedores.BackgroundImage")));
            this.btnProveedores.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProveedores.ButtonText = "";
            this.btnProveedores.ButtonTextMarginLeft = 0;
            this.btnProveedores.ColorContrastOnClick = 45;
            this.btnProveedores.ColorContrastOnHover = 45;
            this.btnProveedores.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnProveedores.CustomizableEdges = borderEdges3;
            this.btnProveedores.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProveedores.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProveedores.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProveedores.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProveedores.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnProveedores.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProveedores.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProveedores.ForeColor = System.Drawing.Color.White;
            this.btnProveedores.IconLeft = global::Artemis.Properties.Resources.delivery_truck;
            this.btnProveedores.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProveedores.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProveedores.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProveedores.IconMarginLeft = 11;
            this.btnProveedores.IconPadding = 10;
            this.btnProveedores.IconRight = null;
            this.btnProveedores.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProveedores.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProveedores.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProveedores.IconSize = 25;
            this.btnProveedores.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProveedores.IdleBorderRadius = 0;
            this.btnProveedores.IdleBorderThickness = 0;
            this.btnProveedores.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProveedores.IdleIconLeftImage = global::Artemis.Properties.Resources.delivery_truck;
            this.btnProveedores.IdleIconRightImage = null;
            this.btnProveedores.IndicateFocus = false;
            this.btnProveedores.Location = new System.Drawing.Point(0, 195);
            this.btnProveedores.Name = "btnProveedores";
            this.btnProveedores.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProveedores.OnDisabledState.BorderRadius = 5;
            this.btnProveedores.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProveedores.OnDisabledState.BorderThickness = 1;
            this.btnProveedores.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProveedores.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProveedores.OnDisabledState.IconLeftImage = null;
            this.btnProveedores.OnDisabledState.IconRightImage = null;
            this.btnProveedores.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnProveedores.onHoverState.BorderRadius = 5;
            this.btnProveedores.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProveedores.onHoverState.BorderThickness = 1;
            this.btnProveedores.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnProveedores.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProveedores.onHoverState.IconLeftImage = null;
            this.btnProveedores.onHoverState.IconRightImage = null;
            this.btnProveedores.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnProveedores.OnIdleState.BorderRadius = 5;
            this.btnProveedores.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProveedores.OnIdleState.BorderThickness = 1;
            this.btnProveedores.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnProveedores.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProveedores.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.delivery_truck;
            this.btnProveedores.OnIdleState.IconRightImage = null;
            this.btnProveedores.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnProveedores.OnPressedState.BorderRadius = 5;
            this.btnProveedores.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProveedores.OnPressedState.BorderThickness = 1;
            this.btnProveedores.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnProveedores.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProveedores.OnPressedState.IconLeftImage = null;
            this.btnProveedores.OnPressedState.IconRightImage = null;
            this.btnProveedores.Size = new System.Drawing.Size(46, 39);
            this.btnProveedores.TabIndex = 5;
            this.btnProveedores.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProveedores.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProveedores.TextMarginLeft = 0;
            this.btnProveedores.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProveedores.UseDefaultRadiusAndThickness = true;
            this.btnProveedores.Click += new System.EventHandler(this.BtnProveedores_Click);
            // 
            // btnProductos
            // 
            this.btnProductos.AllowAnimations = true;
            this.btnProductos.AllowMouseEffects = true;
            this.btnProductos.AllowToggling = false;
            this.btnProductos.AnimationSpeed = 200;
            this.btnProductos.AutoGenerateColors = false;
            this.btnProductos.AutoRoundBorders = false;
            this.btnProductos.AutoSizeLeftIcon = true;
            this.btnProductos.AutoSizeRightIcon = true;
            this.btnProductos.BackColor = System.Drawing.Color.Transparent;
            this.btnProductos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnProductos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnProductos.BackgroundImage")));
            this.btnProductos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductos.ButtonText = "";
            this.btnProductos.ButtonTextMarginLeft = 0;
            this.btnProductos.ColorContrastOnClick = 45;
            this.btnProductos.ColorContrastOnHover = 45;
            this.btnProductos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnProductos.CustomizableEdges = borderEdges4;
            this.btnProductos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnProductos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductos.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnProductos.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnProductos.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnProductos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnProductos.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnProductos.ForeColor = System.Drawing.Color.White;
            this.btnProductos.IconLeft = global::Artemis.Properties.Resources.box;
            this.btnProductos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnProductos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnProductos.IconMarginLeft = 11;
            this.btnProductos.IconPadding = 10;
            this.btnProductos.IconRight = null;
            this.btnProductos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnProductos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnProductos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnProductos.IconSize = 25;
            this.btnProductos.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnProductos.IdleBorderRadius = 0;
            this.btnProductos.IdleBorderThickness = 0;
            this.btnProductos.IdleFillColor = System.Drawing.Color.Empty;
            this.btnProductos.IdleIconLeftImage = global::Artemis.Properties.Resources.box;
            this.btnProductos.IdleIconRightImage = null;
            this.btnProductos.IndicateFocus = false;
            this.btnProductos.Location = new System.Drawing.Point(0, 156);
            this.btnProductos.Name = "btnProductos";
            this.btnProductos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnProductos.OnDisabledState.BorderRadius = 5;
            this.btnProductos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductos.OnDisabledState.BorderThickness = 1;
            this.btnProductos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnProductos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnProductos.OnDisabledState.IconLeftImage = null;
            this.btnProductos.OnDisabledState.IconRightImage = null;
            this.btnProductos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnProductos.onHoverState.BorderRadius = 5;
            this.btnProductos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductos.onHoverState.BorderThickness = 1;
            this.btnProductos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnProductos.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnProductos.onHoverState.IconLeftImage = null;
            this.btnProductos.onHoverState.IconRightImage = null;
            this.btnProductos.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnProductos.OnIdleState.BorderRadius = 5;
            this.btnProductos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductos.OnIdleState.BorderThickness = 1;
            this.btnProductos.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnProductos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnProductos.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.box;
            this.btnProductos.OnIdleState.IconRightImage = null;
            this.btnProductos.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnProductos.OnPressedState.BorderRadius = 5;
            this.btnProductos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnProductos.OnPressedState.BorderThickness = 1;
            this.btnProductos.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnProductos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnProductos.OnPressedState.IconLeftImage = null;
            this.btnProductos.OnPressedState.IconRightImage = null;
            this.btnProductos.Size = new System.Drawing.Size(46, 39);
            this.btnProductos.TabIndex = 4;
            this.btnProductos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnProductos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnProductos.TextMarginLeft = 0;
            this.btnProductos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnProductos.UseDefaultRadiusAndThickness = true;
            // 
            // btnEmpleados
            // 
            this.btnEmpleados.AllowAnimations = true;
            this.btnEmpleados.AllowMouseEffects = true;
            this.btnEmpleados.AllowToggling = false;
            this.btnEmpleados.AnimationSpeed = 200;
            this.btnEmpleados.AutoGenerateColors = false;
            this.btnEmpleados.AutoRoundBorders = false;
            this.btnEmpleados.AutoSizeLeftIcon = true;
            this.btnEmpleados.AutoSizeRightIcon = true;
            this.btnEmpleados.BackColor = System.Drawing.Color.Transparent;
            this.btnEmpleados.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnEmpleados.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmpleados.BackgroundImage")));
            this.btnEmpleados.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmpleados.ButtonText = "";
            this.btnEmpleados.ButtonTextMarginLeft = 0;
            this.btnEmpleados.ColorContrastOnClick = 45;
            this.btnEmpleados.ColorContrastOnHover = 45;
            this.btnEmpleados.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnEmpleados.CustomizableEdges = borderEdges5;
            this.btnEmpleados.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmpleados.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmpleados.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnEmpleados.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnEmpleados.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnEmpleados.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmpleados.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEmpleados.ForeColor = System.Drawing.Color.White;
            this.btnEmpleados.IconLeft = global::Artemis.Properties.Resources.empleados;
            this.btnEmpleados.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEmpleados.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmpleados.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEmpleados.IconMarginLeft = 11;
            this.btnEmpleados.IconPadding = 10;
            this.btnEmpleados.IconRight = null;
            this.btnEmpleados.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEmpleados.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEmpleados.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEmpleados.IconSize = 25;
            this.btnEmpleados.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnEmpleados.IdleBorderRadius = 0;
            this.btnEmpleados.IdleBorderThickness = 0;
            this.btnEmpleados.IdleFillColor = System.Drawing.Color.Empty;
            this.btnEmpleados.IdleIconLeftImage = global::Artemis.Properties.Resources.empleados;
            this.btnEmpleados.IdleIconRightImage = null;
            this.btnEmpleados.IndicateFocus = false;
            this.btnEmpleados.Location = new System.Drawing.Point(0, 117);
            this.btnEmpleados.Name = "btnEmpleados";
            this.btnEmpleados.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmpleados.OnDisabledState.BorderRadius = 5;
            this.btnEmpleados.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmpleados.OnDisabledState.BorderThickness = 1;
            this.btnEmpleados.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmpleados.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmpleados.OnDisabledState.IconLeftImage = null;
            this.btnEmpleados.OnDisabledState.IconRightImage = null;
            this.btnEmpleados.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnEmpleados.onHoverState.BorderRadius = 5;
            this.btnEmpleados.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmpleados.onHoverState.BorderThickness = 1;
            this.btnEmpleados.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnEmpleados.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEmpleados.onHoverState.IconLeftImage = null;
            this.btnEmpleados.onHoverState.IconRightImage = null;
            this.btnEmpleados.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnEmpleados.OnIdleState.BorderRadius = 5;
            this.btnEmpleados.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmpleados.OnIdleState.BorderThickness = 1;
            this.btnEmpleados.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnEmpleados.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEmpleados.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.empleados;
            this.btnEmpleados.OnIdleState.IconRightImage = null;
            this.btnEmpleados.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnEmpleados.OnPressedState.BorderRadius = 5;
            this.btnEmpleados.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmpleados.OnPressedState.BorderThickness = 1;
            this.btnEmpleados.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnEmpleados.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEmpleados.OnPressedState.IconLeftImage = null;
            this.btnEmpleados.OnPressedState.IconRightImage = null;
            this.btnEmpleados.Size = new System.Drawing.Size(46, 39);
            this.btnEmpleados.TabIndex = 3;
            this.btnEmpleados.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmpleados.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEmpleados.TextMarginLeft = 0;
            this.btnEmpleados.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEmpleados.UseDefaultRadiusAndThickness = true;
            // 
            // btnCompras
            // 
            this.btnCompras.AllowAnimations = true;
            this.btnCompras.AllowMouseEffects = true;
            this.btnCompras.AllowToggling = false;
            this.btnCompras.AnimationSpeed = 200;
            this.btnCompras.AutoGenerateColors = false;
            this.btnCompras.AutoRoundBorders = false;
            this.btnCompras.AutoSizeLeftIcon = true;
            this.btnCompras.AutoSizeRightIcon = true;
            this.btnCompras.BackColor = System.Drawing.Color.Transparent;
            this.btnCompras.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCompras.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCompras.BackgroundImage")));
            this.btnCompras.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompras.ButtonText = "";
            this.btnCompras.ButtonTextMarginLeft = 0;
            this.btnCompras.ColorContrastOnClick = 45;
            this.btnCompras.ColorContrastOnHover = 45;
            this.btnCompras.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCompras.CustomizableEdges = borderEdges6;
            this.btnCompras.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCompras.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCompras.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCompras.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCompras.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCompras.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCompras.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCompras.ForeColor = System.Drawing.Color.White;
            this.btnCompras.IconLeft = global::Artemis.Properties.Resources.carts;
            this.btnCompras.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCompras.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCompras.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCompras.IconMarginLeft = 11;
            this.btnCompras.IconPadding = 10;
            this.btnCompras.IconRight = null;
            this.btnCompras.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCompras.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCompras.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCompras.IconSize = 25;
            this.btnCompras.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCompras.IdleBorderRadius = 0;
            this.btnCompras.IdleBorderThickness = 0;
            this.btnCompras.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCompras.IdleIconLeftImage = global::Artemis.Properties.Resources.carts;
            this.btnCompras.IdleIconRightImage = null;
            this.btnCompras.IndicateFocus = false;
            this.btnCompras.Location = new System.Drawing.Point(0, 78);
            this.btnCompras.Name = "btnCompras";
            this.btnCompras.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCompras.OnDisabledState.BorderRadius = 5;
            this.btnCompras.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompras.OnDisabledState.BorderThickness = 1;
            this.btnCompras.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCompras.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCompras.OnDisabledState.IconLeftImage = null;
            this.btnCompras.OnDisabledState.IconRightImage = null;
            this.btnCompras.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnCompras.onHoverState.BorderRadius = 5;
            this.btnCompras.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompras.onHoverState.BorderThickness = 1;
            this.btnCompras.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnCompras.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCompras.onHoverState.IconLeftImage = null;
            this.btnCompras.onHoverState.IconRightImage = null;
            this.btnCompras.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnCompras.OnIdleState.BorderRadius = 5;
            this.btnCompras.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompras.OnIdleState.BorderThickness = 1;
            this.btnCompras.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnCompras.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCompras.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.carts;
            this.btnCompras.OnIdleState.IconRightImage = null;
            this.btnCompras.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnCompras.OnPressedState.BorderRadius = 5;
            this.btnCompras.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCompras.OnPressedState.BorderThickness = 1;
            this.btnCompras.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnCompras.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCompras.OnPressedState.IconLeftImage = null;
            this.btnCompras.OnPressedState.IconRightImage = null;
            this.btnCompras.Size = new System.Drawing.Size(46, 39);
            this.btnCompras.TabIndex = 2;
            this.btnCompras.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCompras.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCompras.TextMarginLeft = 0;
            this.btnCompras.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCompras.UseDefaultRadiusAndThickness = true;
            // 
            // btnClientes
            // 
            this.btnClientes.AllowAnimations = true;
            this.btnClientes.AllowMouseEffects = true;
            this.btnClientes.AllowToggling = false;
            this.btnClientes.AnimationSpeed = 200;
            this.btnClientes.AutoGenerateColors = false;
            this.btnClientes.AutoRoundBorders = false;
            this.btnClientes.AutoSizeLeftIcon = true;
            this.btnClientes.AutoSizeRightIcon = true;
            this.btnClientes.BackColor = System.Drawing.Color.Transparent;
            this.btnClientes.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnClientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnClientes.BackgroundImage")));
            this.btnClientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClientes.ButtonText = "";
            this.btnClientes.ButtonTextMarginLeft = 0;
            this.btnClientes.ColorContrastOnClick = 45;
            this.btnClientes.ColorContrastOnHover = 45;
            this.btnClientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnClientes.CustomizableEdges = borderEdges7;
            this.btnClientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClientes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClientes.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnClientes.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnClientes.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnClientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnClientes.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClientes.ForeColor = System.Drawing.Color.White;
            this.btnClientes.IconLeft = global::Artemis.Properties.Resources.team;
            this.btnClientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnClientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnClientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnClientes.IconMarginLeft = 11;
            this.btnClientes.IconPadding = 10;
            this.btnClientes.IconRight = null;
            this.btnClientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnClientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnClientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnClientes.IconSize = 25;
            this.btnClientes.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnClientes.IdleBorderRadius = 0;
            this.btnClientes.IdleBorderThickness = 0;
            this.btnClientes.IdleFillColor = System.Drawing.Color.Empty;
            this.btnClientes.IdleIconLeftImage = global::Artemis.Properties.Resources.team;
            this.btnClientes.IdleIconRightImage = null;
            this.btnClientes.IndicateFocus = false;
            this.btnClientes.Location = new System.Drawing.Point(0, 39);
            this.btnClientes.Name = "btnClientes";
            this.btnClientes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnClientes.OnDisabledState.BorderRadius = 5;
            this.btnClientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClientes.OnDisabledState.BorderThickness = 1;
            this.btnClientes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnClientes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnClientes.OnDisabledState.IconLeftImage = null;
            this.btnClientes.OnDisabledState.IconRightImage = null;
            this.btnClientes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnClientes.onHoverState.BorderRadius = 5;
            this.btnClientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClientes.onHoverState.BorderThickness = 1;
            this.btnClientes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnClientes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnClientes.onHoverState.IconLeftImage = null;
            this.btnClientes.onHoverState.IconRightImage = null;
            this.btnClientes.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnClientes.OnIdleState.BorderRadius = 5;
            this.btnClientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClientes.OnIdleState.BorderThickness = 1;
            this.btnClientes.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnClientes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnClientes.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.team;
            this.btnClientes.OnIdleState.IconRightImage = null;
            this.btnClientes.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnClientes.OnPressedState.BorderRadius = 5;
            this.btnClientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnClientes.OnPressedState.BorderThickness = 1;
            this.btnClientes.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnClientes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnClientes.OnPressedState.IconLeftImage = null;
            this.btnClientes.OnPressedState.IconRightImage = null;
            this.btnClientes.Size = new System.Drawing.Size(46, 39);
            this.btnClientes.TabIndex = 1;
            this.btnClientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnClientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnClientes.TextMarginLeft = 0;
            this.btnClientes.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnClientes.UseDefaultRadiusAndThickness = true;
            this.btnClientes.Click += new System.EventHandler(this.BtnClientes_Click);
            // 
            // btnCategorias
            // 
            this.btnCategorias.AllowAnimations = true;
            this.btnCategorias.AllowMouseEffects = true;
            this.btnCategorias.AllowToggling = false;
            this.btnCategorias.AnimationSpeed = 200;
            this.btnCategorias.AutoGenerateColors = false;
            this.btnCategorias.AutoRoundBorders = false;
            this.btnCategorias.AutoSizeLeftIcon = true;
            this.btnCategorias.AutoSizeRightIcon = true;
            this.btnCategorias.BackColor = System.Drawing.Color.Transparent;
            this.btnCategorias.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCategorias.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategorias.BackgroundImage")));
            this.btnCategorias.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorias.ButtonText = "";
            this.btnCategorias.ButtonTextMarginLeft = 0;
            this.btnCategorias.ColorContrastOnClick = 45;
            this.btnCategorias.ColorContrastOnHover = 45;
            this.btnCategorias.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnCategorias.CustomizableEdges = borderEdges8;
            this.btnCategorias.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategorias.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategorias.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCategorias.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCategorias.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCategorias.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategorias.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCategorias.ForeColor = System.Drawing.Color.White;
            this.btnCategorias.IconLeft = global::Artemis.Properties.Resources.categories;
            this.btnCategorias.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategorias.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategorias.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategorias.IconMarginLeft = 11;
            this.btnCategorias.IconPadding = 10;
            this.btnCategorias.IconRight = null;
            this.btnCategorias.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategorias.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategorias.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCategorias.IconSize = 25;
            this.btnCategorias.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCategorias.IdleBorderRadius = 0;
            this.btnCategorias.IdleBorderThickness = 0;
            this.btnCategorias.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCategorias.IdleIconLeftImage = global::Artemis.Properties.Resources.categories;
            this.btnCategorias.IdleIconRightImage = null;
            this.btnCategorias.IndicateFocus = false;
            this.btnCategorias.Location = new System.Drawing.Point(0, 0);
            this.btnCategorias.Name = "btnCategorias";
            this.btnCategorias.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategorias.OnDisabledState.BorderRadius = 5;
            this.btnCategorias.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorias.OnDisabledState.BorderThickness = 1;
            this.btnCategorias.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategorias.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategorias.OnDisabledState.IconLeftImage = null;
            this.btnCategorias.OnDisabledState.IconRightImage = null;
            this.btnCategorias.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnCategorias.onHoverState.BorderRadius = 5;
            this.btnCategorias.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorias.onHoverState.BorderThickness = 1;
            this.btnCategorias.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.btnCategorias.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategorias.onHoverState.IconLeftImage = null;
            this.btnCategorias.onHoverState.IconRightImage = null;
            this.btnCategorias.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnCategorias.OnIdleState.BorderRadius = 5;
            this.btnCategorias.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorias.OnIdleState.BorderThickness = 1;
            this.btnCategorias.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(15)))), ((int)(((byte)(15)))), ((int)(((byte)(15)))));
            this.btnCategorias.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCategorias.OnIdleState.IconLeftImage = global::Artemis.Properties.Resources.categories;
            this.btnCategorias.OnIdleState.IconRightImage = null;
            this.btnCategorias.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.btnCategorias.OnPressedState.BorderRadius = 5;
            this.btnCategorias.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategorias.OnPressedState.BorderThickness = 1;
            this.btnCategorias.OnPressedState.FillColor = System.Drawing.Color.Black;
            this.btnCategorias.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategorias.OnPressedState.IconLeftImage = null;
            this.btnCategorias.OnPressedState.IconRightImage = null;
            this.btnCategorias.Size = new System.Drawing.Size(46, 39);
            this.btnCategorias.TabIndex = 0;
            this.btnCategorias.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategorias.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategorias.TextMarginLeft = 0;
            this.btnCategorias.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategorias.UseDefaultRadiusAndThickness = true;
            this.btnCategorias.Click += new System.EventHandler(this.BtnCategorias_Click);
            // 
            // pnlPrincipal
            // 
            this.pnlPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPrincipal.Location = new System.Drawing.Point(46, 18);
            this.pnlPrincipal.Name = "pnlPrincipal";
            this.pnlPrincipal.Size = new System.Drawing.Size(1014, 469);
            this.pnlPrincipal.TabIndex = 2;
            // 
            // Principal
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.ClientSize = new System.Drawing.Size(1060, 487);
            this.Controls.Add(this.pnlPrincipal);
            this.Controls.Add(this.pnlSideBar);
            this.Controls.Add(this.pnlTop);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Principal";
            this.Palette = this.paletaDiseños;
            this.PaletteMode = ComponentFactory.Krypton.Toolkit.PaletteMode.Custom;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Principal";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Principal_FormClosing);
            this.pnlSideBar.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private ComponentFactory.Krypton.Toolkit.KryptonPalette paletaDiseños;
        private System.Windows.Forms.Panel pnlTop;
        private System.Windows.Forms.Panel pnlSideBar;
        private System.Windows.Forms.Panel pnlPrincipal;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategorias;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnClientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCompras;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmpleados;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProductos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnProveedores;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUsuarios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVentas;
    }
}