//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Cantidad del registro contiene un valor no admitido por el sistema,.
        /// </summary>
        internal static string CANTIDAD_DEFAULT {
            get {
                return ResourceManager.GetString("CANTIDAD_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña del registro es muy corta. Digite al menos 5 caracteres..
        /// </summary>
        internal static string CONTRASEÑA_CORTA {
            get {
                return ResourceManager.GetString("CONTRASEÑA_CORTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña del registro contiene valores no permitidos por el sistema..
        /// </summary>
        internal static string CONTRASEÑA_DEFAULT {
            get {
                return ResourceManager.GetString("CONTRASEÑA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se reconoce el correo electrónico ingresado..
        /// </summary>
        internal static string CORREO_INCORRECTO {
            get {
                return ResourceManager.GetString("CORREO_INCORRECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del Correo excede la permitida..
        /// </summary>
        internal static string CORREO_LONGITUD_EXCEDIDA {
            get {
                return ResourceManager.GetString("CORREO_LONGITUD_EXCEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Costo de Envío del registro contiene valores negativos..
        /// </summary>
        internal static string COSTO_ENVIO_NEGATIVO {
            get {
                return ResourceManager.GetString("COSTO_ENVIO_NEGATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Descuento del registro contiene valores negativos.
        /// </summary>
        internal static string DESCUENTO_NEGATIVO {
            get {
                return ResourceManager.GetString("DESCUENTO_NEGATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un registro desea realizar una operación pero no se encuentra habilitado..
        /// </summary>
        internal static string ESTADO_DESACTIVADO {
            get {
                return ResourceManager.GetString("ESTADO_DESACTIVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha del registro contiene valores no admitidos por el sistema..
        /// </summary>
        internal static string FECHA_DEFAULT {
            get {
                return ResourceManager.GetString("FECHA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de la Categoría asociada al registro contiene un valor no permitido por el sistema..
        /// </summary>
        internal static string ID_CATEGORIA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_CATEGORIA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del Cliente asociado al registro contiene un valor no permitido por el sistema..
        /// </summary>
        internal static string ID_CLIENTE_DEFAULT {
            get {
                return ResourceManager.GetString("ID_CLIENTE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de la compra asociada al registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_COMPRA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_COMPRA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_DEFAULT {
            get {
                return ResourceManager.GetString("ID_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del Departamento asociado al registro contiene un valor no permitido por el sistema..
        /// </summary>
        internal static string ID_DEPARTAMENTO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_DEPARTAMENTO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del empleado relacionado al registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_EMPLEADO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_EMPLEADO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del Municipio al que está relacionado el registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_MUNICIPIO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_MUNICIPIO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del producto asociado al registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_PRODUCTO_DEFAULT {
            get {
                return ResourceManager.GetString("ID_PRODUCTO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID del proveedor asociado al registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string ID_PROVEEDOR_DEFAULT {
            get {
                return ResourceManager.GetString("ID_PROVEEDOR_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ID de la venta asociada al registro contiene un valor no permitido por el sistema..
        /// </summary>
        internal static string ID_VENTA_DEFAULT {
            get {
                return ResourceManager.GetString("ID_VENTA_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logró encontrar o identificar el modelo..
        /// </summary>
        internal static string MODELO_NULO {
            get {
                return ResourceManager.GetString("MODELO_NULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del registro contiene un valor no admitido por el sistema..
        /// </summary>
        internal static string NOMBRE_DEFAULT {
            get {
                return ResourceManager.GetString("NOMBRE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Primer Apellido del registro contiene valores no admitidos por el sistema..
        /// </summary>
        internal static string PRIMER_APELLIDO_DEFAULT {
            get {
                return ResourceManager.GetString("PRIMER_APELLIDO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Primer Nombre del registro contiene valores no admitidos por el sistema..
        /// </summary>
        internal static string PRIMER_NOMBRE_DEFAULT {
            get {
                return ResourceManager.GetString("PRIMER_NOMBRE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de caracteres del Primer Nombre excede la permitida..
        /// </summary>
        internal static string PRIMER_NOMBRE_LONGITUD_EXCEDIDA {
            get {
                return ResourceManager.GetString("PRIMER_NOMBRE_LONGITUD_EXCEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de caracteres del Segundo Apellido excede la permitida..
        /// </summary>
        internal static string SEGUNDO_APELLIDO_LONGITUD_EXCEDIDA {
            get {
                return ResourceManager.GetString("SEGUNDO_APELLIDO_LONGITUD_EXCEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud de caracteres del Segundo Nombre excede la permitida..
        /// </summary>
        internal static string SEGUNDO_NOMBRE_LONGITUD_EXCEDIDA {
            get {
                return ResourceManager.GetString("SEGUNDO_NOMBRE_LONGITUD_EXCEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logró encontrar un usuario con la información brindada..
        /// </summary>
        internal static string USUARIO_NULO {
            get {
                return ResourceManager.GetString("USUARIO_NULO", resourceCulture);
            }
        }
    }
}
