namespace Artemis.Presentacion.Identity
{
    partial class EditorUsuario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(EditorUsuario));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.formBorderStyle = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.lblTitulo = new System.Windows.Forms.Label();
            this.pnlBotones = new System.Windows.Forms.FlowLayoutPanel();
            this.btnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCancelar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pnlPrincipal = new System.Windows.Forms.Panel();
            this.pnlContraseña = new System.Windows.Forms.TableLayoutPanel();
            this.txtContraseña = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblContraseña = new System.Windows.Forms.Label();
            this.pnlEmpleados = new System.Windows.Forms.TableLayoutPanel();
            this.dgvEmpleados = new System.Windows.Forms.DataGridView();
            this.txtBuscarEmpleado = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblAsignacionUsuario = new System.Windows.Forms.Label();
            this.pnlCaracteristicasCliente = new System.Windows.Forms.TableLayoutPanel();
            this.txtNombreUsuario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRolUsuairo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblCaracteristicasUsuario = new System.Windows.Forms.Label();
            this.txtConfirmarContraseña = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlBotones.SuspendLayout();
            this.pnlPrincipal.SuspendLayout();
            this.pnlContraseña.SuspendLayout();
            this.pnlEmpleados.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvEmpleados)).BeginInit();
            this.pnlCaracteristicasCliente.SuspendLayout();
            this.SuspendLayout();
            // 
            // formBorderStyle
            // 
            this.formBorderStyle.ElipseRadius = 15;
            this.formBorderStyle.TargetControl = this;
            // 
            // lblTitulo
            // 
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblTitulo.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitulo.Location = new System.Drawing.Point(0, 0);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(770, 52);
            this.lblTitulo.TabIndex = 0;
            this.lblTitulo.Text = "Editar Usuario";
            this.lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlBotones
            // 
            this.pnlBotones.Controls.Add(this.btnGuardar);
            this.pnlBotones.Controls.Add(this.btnLimpiar);
            this.pnlBotones.Controls.Add(this.btnCancelar);
            this.pnlBotones.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlBotones.FlowDirection = System.Windows.Forms.FlowDirection.RightToLeft;
            this.pnlBotones.Location = new System.Drawing.Point(0, 371);
            this.pnlBotones.Name = "pnlBotones";
            this.pnlBotones.Size = new System.Drawing.Size(770, 51);
            this.pnlBotones.TabIndex = 1;
            // 
            // btnGuardar
            // 
            this.btnGuardar.AllowAnimations = true;
            this.btnGuardar.AllowMouseEffects = true;
            this.btnGuardar.AllowToggling = false;
            this.btnGuardar.AnimationSpeed = 200;
            this.btnGuardar.AutoGenerateColors = false;
            this.btnGuardar.AutoRoundBorders = false;
            this.btnGuardar.AutoSizeLeftIcon = true;
            this.btnGuardar.AutoSizeRightIcon = true;
            this.btnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardar.BackgroundImage")));
            this.btnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.ButtonText = "Guardar";
            this.btnGuardar.ButtonTextMarginLeft = 0;
            this.btnGuardar.ColorContrastOnClick = 45;
            this.btnGuardar.ColorContrastOnHover = 45;
            this.btnGuardar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnGuardar.CustomizableEdges = borderEdges1;
            this.btnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnGuardar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGuardar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconLeft = null;
            this.btnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardar.IconMarginLeft = 11;
            this.btnGuardar.IconPadding = 10;
            this.btnGuardar.IconRight = null;
            this.btnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardar.IconSize = 25;
            this.btnGuardar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnGuardar.IdleBorderRadius = 0;
            this.btnGuardar.IdleBorderThickness = 0;
            this.btnGuardar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnGuardar.IdleIconLeftImage = null;
            this.btnGuardar.IdleIconRightImage = null;
            this.btnGuardar.IndicateFocus = false;
            this.btnGuardar.Location = new System.Drawing.Point(617, 3);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.OnDisabledState.BorderRadius = 15;
            this.btnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnDisabledState.BorderThickness = 1;
            this.btnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.OnDisabledState.IconLeftImage = null;
            this.btnGuardar.OnDisabledState.IconRightImage = null;
            this.btnGuardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.onHoverState.BorderRadius = 15;
            this.btnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.onHoverState.BorderThickness = 1;
            this.btnGuardar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardar.onHoverState.IconLeftImage = null;
            this.btnGuardar.onHoverState.IconRightImage = null;
            this.btnGuardar.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.BorderRadius = 15;
            this.btnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnIdleState.BorderThickness = 1;
            this.btnGuardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.IconLeftImage = null;
            this.btnGuardar.OnIdleState.IconRightImage = null;
            this.btnGuardar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.BorderRadius = 15;
            this.btnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGuardar.OnPressedState.BorderThickness = 1;
            this.btnGuardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.IconLeftImage = null;
            this.btnGuardar.OnPressedState.IconRightImage = null;
            this.btnGuardar.Size = new System.Drawing.Size(150, 39);
            this.btnGuardar.TabIndex = 0;
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardar.TextMarginLeft = 0;
            this.btnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardar.UseDefaultRadiusAndThickness = true;
            this.btnGuardar.Click += new System.EventHandler(this.BtnGuardar_Click);
            // 
            // btnLimpiar
            // 
            this.btnLimpiar.AllowAnimations = true;
            this.btnLimpiar.AllowMouseEffects = true;
            this.btnLimpiar.AllowToggling = false;
            this.btnLimpiar.AnimationSpeed = 200;
            this.btnLimpiar.AutoGenerateColors = false;
            this.btnLimpiar.AutoRoundBorders = false;
            this.btnLimpiar.AutoSizeLeftIcon = true;
            this.btnLimpiar.AutoSizeRightIcon = true;
            this.btnLimpiar.BackColor = System.Drawing.Color.Transparent;
            this.btnLimpiar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnLimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLimpiar.BackgroundImage")));
            this.btnLimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.ButtonText = "Limpiar";
            this.btnLimpiar.ButtonTextMarginLeft = 0;
            this.btnLimpiar.ColorContrastOnClick = 45;
            this.btnLimpiar.ColorContrastOnHover = 45;
            this.btnLimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLimpiar.CustomizableEdges = borderEdges2;
            this.btnLimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnLimpiar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnLimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLimpiar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLimpiar.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.IconLeft = null;
            this.btnLimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLimpiar.IconMarginLeft = 11;
            this.btnLimpiar.IconPadding = 10;
            this.btnLimpiar.IconRight = null;
            this.btnLimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLimpiar.IconSize = 25;
            this.btnLimpiar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnLimpiar.IdleBorderRadius = 0;
            this.btnLimpiar.IdleBorderThickness = 0;
            this.btnLimpiar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnLimpiar.IdleIconLeftImage = null;
            this.btnLimpiar.IdleIconRightImage = null;
            this.btnLimpiar.IndicateFocus = false;
            this.btnLimpiar.Location = new System.Drawing.Point(461, 3);
            this.btnLimpiar.Name = "btnLimpiar";
            this.btnLimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLimpiar.OnDisabledState.BorderRadius = 15;
            this.btnLimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnDisabledState.BorderThickness = 1;
            this.btnLimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLimpiar.OnDisabledState.IconLeftImage = null;
            this.btnLimpiar.OnDisabledState.IconRightImage = null;
            this.btnLimpiar.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnLimpiar.onHoverState.BorderRadius = 15;
            this.btnLimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.onHoverState.BorderThickness = 1;
            this.btnLimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLimpiar.onHoverState.IconLeftImage = null;
            this.btnLimpiar.onHoverState.IconRightImage = null;
            this.btnLimpiar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.OnIdleState.BorderRadius = 15;
            this.btnLimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnIdleState.BorderThickness = 1;
            this.btnLimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLimpiar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.OnIdleState.IconLeftImage = null;
            this.btnLimpiar.OnIdleState.IconRightImage = null;
            this.btnLimpiar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnLimpiar.OnPressedState.BorderRadius = 15;
            this.btnLimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLimpiar.OnPressedState.BorderThickness = 1;
            this.btnLimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnLimpiar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnLimpiar.OnPressedState.IconLeftImage = null;
            this.btnLimpiar.OnPressedState.IconRightImage = null;
            this.btnLimpiar.Size = new System.Drawing.Size(150, 39);
            this.btnLimpiar.TabIndex = 1;
            this.btnLimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLimpiar.TextMarginLeft = 0;
            this.btnLimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLimpiar.UseDefaultRadiusAndThickness = true;
            this.btnLimpiar.Click += new System.EventHandler(this.BtnLimpiar_Click);
            // 
            // btnCancelar
            // 
            this.btnCancelar.AllowAnimations = true;
            this.btnCancelar.AllowMouseEffects = true;
            this.btnCancelar.AllowToggling = false;
            this.btnCancelar.AnimationSpeed = 200;
            this.btnCancelar.AutoGenerateColors = false;
            this.btnCancelar.AutoRoundBorders = false;
            this.btnCancelar.AutoSizeLeftIcon = true;
            this.btnCancelar.AutoSizeRightIcon = true;
            this.btnCancelar.BackColor = System.Drawing.Color.Transparent;
            this.btnCancelar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnCancelar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancelar.BackgroundImage")));
            this.btnCancelar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.ButtonText = "Cancelar";
            this.btnCancelar.ButtonTextMarginLeft = 0;
            this.btnCancelar.ColorContrastOnClick = 45;
            this.btnCancelar.ColorContrastOnHover = 45;
            this.btnCancelar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCancelar.CustomizableEdges = borderEdges3;
            this.btnCancelar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCancelar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnCancelar.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCancelar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancelar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelar.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.IconLeft = null;
            this.btnCancelar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancelar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancelar.IconMarginLeft = 11;
            this.btnCancelar.IconPadding = 10;
            this.btnCancelar.IconRight = null;
            this.btnCancelar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancelar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancelar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancelar.IconSize = 25;
            this.btnCancelar.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCancelar.IdleBorderRadius = 0;
            this.btnCancelar.IdleBorderThickness = 0;
            this.btnCancelar.IdleFillColor = System.Drawing.Color.Empty;
            this.btnCancelar.IdleIconLeftImage = null;
            this.btnCancelar.IdleIconRightImage = null;
            this.btnCancelar.IndicateFocus = false;
            this.btnCancelar.Location = new System.Drawing.Point(305, 3);
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancelar.OnDisabledState.BorderRadius = 15;
            this.btnCancelar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnDisabledState.BorderThickness = 1;
            this.btnCancelar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancelar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancelar.OnDisabledState.IconLeftImage = null;
            this.btnCancelar.OnDisabledState.IconRightImage = null;
            this.btnCancelar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.btnCancelar.onHoverState.BorderRadius = 15;
            this.btnCancelar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.onHoverState.BorderThickness = 1;
            this.btnCancelar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.onHoverState.IconLeftImage = null;
            this.btnCancelar.onHoverState.IconRightImage = null;
            this.btnCancelar.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnCancelar.OnIdleState.BorderRadius = 15;
            this.btnCancelar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnIdleState.BorderThickness = 1;
            this.btnCancelar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.OnIdleState.IconLeftImage = null;
            this.btnCancelar.OnIdleState.IconRightImage = null;
            this.btnCancelar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.BorderRadius = 15;
            this.btnCancelar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancelar.OnPressedState.BorderThickness = 1;
            this.btnCancelar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnCancelar.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnCancelar.OnPressedState.IconLeftImage = null;
            this.btnCancelar.OnPressedState.IconRightImage = null;
            this.btnCancelar.Size = new System.Drawing.Size(150, 39);
            this.btnCancelar.TabIndex = 2;
            this.btnCancelar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancelar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancelar.TextMarginLeft = 0;
            this.btnCancelar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancelar.UseDefaultRadiusAndThickness = true;
            this.btnCancelar.Click += new System.EventHandler(this.BtnCancelar_Click);
            // 
            // pnlPrincipal
            // 
            this.pnlPrincipal.AutoScroll = true;
            this.pnlPrincipal.Controls.Add(this.pnlContraseña);
            this.pnlPrincipal.Controls.Add(this.lblContraseña);
            this.pnlPrincipal.Controls.Add(this.pnlEmpleados);
            this.pnlPrincipal.Controls.Add(this.lblAsignacionUsuario);
            this.pnlPrincipal.Controls.Add(this.pnlCaracteristicasCliente);
            this.pnlPrincipal.Controls.Add(this.lblCaracteristicasUsuario);
            this.pnlPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlPrincipal.Location = new System.Drawing.Point(0, 52);
            this.pnlPrincipal.Name = "pnlPrincipal";
            this.pnlPrincipal.Size = new System.Drawing.Size(770, 319);
            this.pnlPrincipal.TabIndex = 2;
            // 
            // pnlContraseña
            // 
            this.pnlContraseña.ColumnCount = 4;
            this.pnlContraseña.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.266667F));
            this.pnlContraseña.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 95.73333F));
            this.pnlContraseña.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 357F));
            this.pnlContraseña.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 19F));
            this.pnlContraseña.Controls.Add(this.txtContraseña, 1, 0);
            this.pnlContraseña.Controls.Add(this.txtConfirmarContraseña, 2, 0);
            this.pnlContraseña.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlContraseña.Location = new System.Drawing.Point(0, 354);
            this.pnlContraseña.Name = "pnlContraseña";
            this.pnlContraseña.RowCount = 2;
            this.pnlContraseña.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 70.96774F));
            this.pnlContraseña.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 29.03226F));
            this.pnlContraseña.Size = new System.Drawing.Size(753, 62);
            this.pnlContraseña.TabIndex = 7;
            // 
            // txtContraseña
            // 
            this.txtContraseña.AcceptsReturn = false;
            this.txtContraseña.AcceptsTab = false;
            this.txtContraseña.AnimationSpeed = 200;
            this.txtContraseña.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtContraseña.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtContraseña.AutoSizeHeight = true;
            this.txtContraseña.BackColor = System.Drawing.Color.White;
            this.txtContraseña.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtContraseña.BackgroundImage")));
            this.txtContraseña.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtContraseña.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtContraseña.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtContraseña.BorderColorIdle = System.Drawing.Color.White;
            this.txtContraseña.BorderRadius = 15;
            this.txtContraseña.BorderThickness = 1;
            this.txtContraseña.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtContraseña.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContraseña.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtContraseña.DefaultText = "";
            this.txtContraseña.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtContraseña.FillColor = System.Drawing.Color.White;
            this.txtContraseña.ForeColor = System.Drawing.Color.Black;
            this.txtContraseña.HideSelection = true;
            this.txtContraseña.IconLeft = global::Artemis.Properties.Resources._lock;
            this.txtContraseña.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContraseña.IconPadding = 10;
            this.txtContraseña.IconRight = null;
            this.txtContraseña.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtContraseña.Lines = new string[0];
            this.txtContraseña.Location = new System.Drawing.Point(19, 3);
            this.txtContraseña.MaxLength = 32767;
            this.txtContraseña.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtContraseña.Modified = false;
            this.txtContraseña.Multiline = false;
            this.txtContraseña.Name = "txtContraseña";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties1.FillColor = System.Drawing.Color.White;
            stateProperties1.ForeColor = System.Drawing.Color.Black;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtContraseña.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtContraseña.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties3.FillColor = System.Drawing.Color.White;
            stateProperties3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtContraseña.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtContraseña.OnIdleState = stateProperties4;
            this.txtContraseña.Padding = new System.Windows.Forms.Padding(3);
            this.txtContraseña.PasswordChar = '\0';
            this.txtContraseña.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtContraseña.PlaceholderText = "Contraseña";
            this.txtContraseña.ReadOnly = false;
            this.txtContraseña.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtContraseña.SelectedText = "";
            this.txtContraseña.SelectionLength = 0;
            this.txtContraseña.SelectionStart = 0;
            this.txtContraseña.ShortcutsEnabled = true;
            this.txtContraseña.Size = new System.Drawing.Size(354, 38);
            this.txtContraseña.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtContraseña.TabIndex = 0;
            this.txtContraseña.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtContraseña.TextMarginBottom = 0;
            this.txtContraseña.TextMarginLeft = 8;
            this.txtContraseña.TextMarginTop = 1;
            this.txtContraseña.TextPlaceholder = "Contraseña";
            this.txtContraseña.UseSystemPasswordChar = false;
            this.txtContraseña.WordWrap = true;
            // 
            // lblContraseña
            // 
            this.lblContraseña.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblContraseña.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblContraseña.Location = new System.Drawing.Point(0, 307);
            this.lblContraseña.Name = "lblContraseña";
            this.lblContraseña.Size = new System.Drawing.Size(753, 47);
            this.lblContraseña.TabIndex = 6;
            this.lblContraseña.Text = "Ayúdenos a mantener la cuenta segura.";
            this.lblContraseña.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlEmpleados
            // 
            this.pnlEmpleados.ColumnCount = 3;
            this.pnlEmpleados.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2.403204F));
            this.pnlEmpleados.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 97.59679F));
            this.pnlEmpleados.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.pnlEmpleados.Controls.Add(this.dgvEmpleados, 1, 1);
            this.pnlEmpleados.Controls.Add(this.txtBuscarEmpleado, 1, 0);
            this.pnlEmpleados.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlEmpleados.Location = new System.Drawing.Point(0, 124);
            this.pnlEmpleados.Name = "pnlEmpleados";
            this.pnlEmpleados.RowCount = 2;
            this.pnlEmpleados.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20.21858F));
            this.pnlEmpleados.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 79.78142F));
            this.pnlEmpleados.Size = new System.Drawing.Size(753, 183);
            this.pnlEmpleados.TabIndex = 3;
            // 
            // dgvEmpleados
            // 
            this.dgvEmpleados.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this.dgvEmpleados.BackgroundColor = System.Drawing.Color.White;
            this.dgvEmpleados.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvEmpleados.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvEmpleados.ColumnHeadersHeight = 30;
            this.dgvEmpleados.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvEmpleados.EnableHeadersVisualStyles = false;
            this.dgvEmpleados.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            this.dgvEmpleados.Location = new System.Drawing.Point(20, 40);
            this.dgvEmpleados.Name = "dgvEmpleados";
            this.dgvEmpleados.ReadOnly = true;
            this.dgvEmpleados.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(92)))), ((int)(((byte)(50)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvEmpleados.RowHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvEmpleados.RowHeadersVisible = false;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(157)))), ((int)(((byte)(85)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(92)))), ((int)(((byte)(50)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            this.dgvEmpleados.RowsDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvEmpleados.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvEmpleados.Size = new System.Drawing.Size(704, 140);
            this.dgvEmpleados.TabIndex = 5;
            // 
            // txtBuscarEmpleado
            // 
            this.txtBuscarEmpleado.AcceptsReturn = false;
            this.txtBuscarEmpleado.AcceptsTab = false;
            this.txtBuscarEmpleado.AnimationSpeed = 200;
            this.txtBuscarEmpleado.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBuscarEmpleado.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBuscarEmpleado.AutoSizeHeight = true;
            this.txtBuscarEmpleado.BackColor = System.Drawing.Color.Transparent;
            this.txtBuscarEmpleado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBuscarEmpleado.BackgroundImage")));
            this.txtBuscarEmpleado.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtBuscarEmpleado.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBuscarEmpleado.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtBuscarEmpleado.BorderColorIdle = System.Drawing.Color.White;
            this.txtBuscarEmpleado.BorderRadius = 15;
            this.txtBuscarEmpleado.BorderThickness = 1;
            this.txtBuscarEmpleado.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBuscarEmpleado.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscarEmpleado.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBuscarEmpleado.DefaultText = "";
            this.txtBuscarEmpleado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtBuscarEmpleado.FillColor = System.Drawing.Color.White;
            this.txtBuscarEmpleado.ForeColor = System.Drawing.Color.Black;
            this.txtBuscarEmpleado.HideSelection = true;
            this.txtBuscarEmpleado.IconLeft = global::Artemis.Properties.Resources.search;
            this.txtBuscarEmpleado.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscarEmpleado.IconPadding = 8;
            this.txtBuscarEmpleado.IconRight = null;
            this.txtBuscarEmpleado.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBuscarEmpleado.Lines = new string[0];
            this.txtBuscarEmpleado.Location = new System.Drawing.Point(20, 3);
            this.txtBuscarEmpleado.MaxLength = 32767;
            this.txtBuscarEmpleado.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBuscarEmpleado.Modified = false;
            this.txtBuscarEmpleado.Multiline = false;
            this.txtBuscarEmpleado.Name = "txtBuscarEmpleado";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties9.FillColor = System.Drawing.Color.White;
            stateProperties9.ForeColor = System.Drawing.Color.Black;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtBuscarEmpleado.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBuscarEmpleado.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties11.FillColor = System.Drawing.Color.White;
            stateProperties11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtBuscarEmpleado.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtBuscarEmpleado.OnIdleState = stateProperties12;
            this.txtBuscarEmpleado.Padding = new System.Windows.Forms.Padding(3);
            this.txtBuscarEmpleado.PasswordChar = '\0';
            this.txtBuscarEmpleado.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtBuscarEmpleado.PlaceholderText = "Buscar";
            this.txtBuscarEmpleado.ReadOnly = false;
            this.txtBuscarEmpleado.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBuscarEmpleado.SelectedText = "";
            this.txtBuscarEmpleado.SelectionLength = 0;
            this.txtBuscarEmpleado.SelectionStart = 0;
            this.txtBuscarEmpleado.ShortcutsEnabled = true;
            this.txtBuscarEmpleado.Size = new System.Drawing.Size(704, 31);
            this.txtBuscarEmpleado.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtBuscarEmpleado.TabIndex = 0;
            this.txtBuscarEmpleado.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBuscarEmpleado.TextMarginBottom = 0;
            this.txtBuscarEmpleado.TextMarginLeft = 8;
            this.txtBuscarEmpleado.TextMarginTop = 1;
            this.txtBuscarEmpleado.TextPlaceholder = "Buscar";
            this.txtBuscarEmpleado.UseSystemPasswordChar = false;
            this.txtBuscarEmpleado.WordWrap = true;
            this.txtBuscarEmpleado.TextChange += new System.EventHandler(this.TxtBuscarEmpleado_TextChange);
            // 
            // lblAsignacionUsuario
            // 
            this.lblAsignacionUsuario.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblAsignacionUsuario.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblAsignacionUsuario.Location = new System.Drawing.Point(0, 85);
            this.lblAsignacionUsuario.Name = "lblAsignacionUsuario";
            this.lblAsignacionUsuario.Size = new System.Drawing.Size(753, 39);
            this.lblAsignacionUsuario.TabIndex = 2;
            this.lblAsignacionUsuario.Text = "¿De quién es este usuario?";
            this.lblAsignacionUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // pnlCaracteristicasCliente
            // 
            this.pnlCaracteristicasCliente.ColumnCount = 4;
            this.pnlCaracteristicasCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 4.947917F));
            this.pnlCaracteristicasCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 95.05209F));
            this.pnlCaracteristicasCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 364F));
            this.pnlCaracteristicasCliente.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 27F));
            this.pnlCaracteristicasCliente.Controls.Add(this.txtNombreUsuario, 1, 0);
            this.pnlCaracteristicasCliente.Controls.Add(this.txtRolUsuairo, 2, 0);
            this.pnlCaracteristicasCliente.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlCaracteristicasCliente.Location = new System.Drawing.Point(0, 41);
            this.pnlCaracteristicasCliente.Name = "pnlCaracteristicasCliente";
            this.pnlCaracteristicasCliente.RowCount = 1;
            this.pnlCaracteristicasCliente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlCaracteristicasCliente.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.pnlCaracteristicasCliente.Size = new System.Drawing.Size(753, 44);
            this.pnlCaracteristicasCliente.TabIndex = 1;
            // 
            // txtNombreUsuario
            // 
            this.txtNombreUsuario.AcceptsReturn = false;
            this.txtNombreUsuario.AcceptsTab = false;
            this.txtNombreUsuario.AnimationSpeed = 200;
            this.txtNombreUsuario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombreUsuario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombreUsuario.AutoSizeHeight = true;
            this.txtNombreUsuario.BackColor = System.Drawing.Color.Transparent;
            this.txtNombreUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombreUsuario.BackgroundImage")));
            this.txtNombreUsuario.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtNombreUsuario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombreUsuario.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtNombreUsuario.BorderColorIdle = System.Drawing.Color.White;
            this.txtNombreUsuario.BorderRadius = 15;
            this.txtNombreUsuario.BorderThickness = 1;
            this.txtNombreUsuario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombreUsuario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombreUsuario.DefaultText = "";
            this.txtNombreUsuario.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtNombreUsuario.FillColor = System.Drawing.Color.White;
            this.txtNombreUsuario.ForeColor = System.Drawing.Color.Black;
            this.txtNombreUsuario.HideSelection = true;
            this.txtNombreUsuario.IconLeft = null;
            this.txtNombreUsuario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.IconPadding = 10;
            this.txtNombreUsuario.IconRight = null;
            this.txtNombreUsuario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreUsuario.Lines = new string[0];
            this.txtNombreUsuario.Location = new System.Drawing.Point(20, 3);
            this.txtNombreUsuario.MaxLength = 32767;
            this.txtNombreUsuario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombreUsuario.Modified = false;
            this.txtNombreUsuario.Multiline = false;
            this.txtNombreUsuario.Name = "txtNombreUsuario";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties13.FillColor = System.Drawing.Color.White;
            stateProperties13.ForeColor = System.Drawing.Color.Black;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtNombreUsuario.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombreUsuario.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties15.FillColor = System.Drawing.Color.White;
            stateProperties15.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtNombreUsuario.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtNombreUsuario.OnIdleState = stateProperties16;
            this.txtNombreUsuario.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombreUsuario.PasswordChar = '\0';
            this.txtNombreUsuario.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtNombreUsuario.PlaceholderText = "Nombre de usuario";
            this.txtNombreUsuario.ReadOnly = false;
            this.txtNombreUsuario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombreUsuario.SelectedText = "";
            this.txtNombreUsuario.SelectionLength = 0;
            this.txtNombreUsuario.SelectionStart = 0;
            this.txtNombreUsuario.ShortcutsEnabled = true;
            this.txtNombreUsuario.Size = new System.Drawing.Size(338, 38);
            this.txtNombreUsuario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombreUsuario.TabIndex = 0;
            this.txtNombreUsuario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombreUsuario.TextMarginBottom = 0;
            this.txtNombreUsuario.TextMarginLeft = 3;
            this.txtNombreUsuario.TextMarginTop = 1;
            this.txtNombreUsuario.TextPlaceholder = "Nombre de usuario";
            this.txtNombreUsuario.UseSystemPasswordChar = false;
            this.txtNombreUsuario.WordWrap = true;
            // 
            // txtRolUsuairo
            // 
            this.txtRolUsuairo.AcceptsReturn = false;
            this.txtRolUsuairo.AcceptsTab = false;
            this.txtRolUsuairo.AnimationSpeed = 200;
            this.txtRolUsuairo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRolUsuairo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRolUsuairo.AutoSizeHeight = true;
            this.txtRolUsuairo.BackColor = System.Drawing.Color.Transparent;
            this.txtRolUsuairo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRolUsuairo.BackgroundImage")));
            this.txtRolUsuairo.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtRolUsuairo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRolUsuairo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtRolUsuairo.BorderColorIdle = System.Drawing.Color.White;
            this.txtRolUsuairo.BorderRadius = 15;
            this.txtRolUsuairo.BorderThickness = 1;
            this.txtRolUsuairo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRolUsuairo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRolUsuairo.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRolUsuairo.DefaultText = "";
            this.txtRolUsuairo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtRolUsuairo.FillColor = System.Drawing.Color.White;
            this.txtRolUsuairo.ForeColor = System.Drawing.Color.Black;
            this.txtRolUsuairo.HideSelection = true;
            this.txtRolUsuairo.IconLeft = null;
            this.txtRolUsuairo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRolUsuairo.IconPadding = 10;
            this.txtRolUsuairo.IconRight = null;
            this.txtRolUsuairo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRolUsuairo.Lines = new string[0];
            this.txtRolUsuairo.Location = new System.Drawing.Point(364, 3);
            this.txtRolUsuairo.MaxLength = 32767;
            this.txtRolUsuairo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRolUsuairo.Modified = false;
            this.txtRolUsuairo.Multiline = false;
            this.txtRolUsuairo.Name = "txtRolUsuairo";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties17.FillColor = System.Drawing.Color.White;
            stateProperties17.ForeColor = System.Drawing.Color.Black;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtRolUsuairo.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRolUsuairo.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties19.FillColor = System.Drawing.Color.White;
            stateProperties19.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtRolUsuairo.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtRolUsuairo.OnIdleState = stateProperties20;
            this.txtRolUsuairo.Padding = new System.Windows.Forms.Padding(3);
            this.txtRolUsuairo.PasswordChar = '\0';
            this.txtRolUsuairo.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtRolUsuairo.PlaceholderText = "Rol";
            this.txtRolUsuairo.ReadOnly = false;
            this.txtRolUsuairo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRolUsuairo.SelectedText = "";
            this.txtRolUsuairo.SelectionLength = 0;
            this.txtRolUsuairo.SelectionStart = 0;
            this.txtRolUsuairo.ShortcutsEnabled = true;
            this.txtRolUsuairo.Size = new System.Drawing.Size(358, 38);
            this.txtRolUsuairo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRolUsuairo.TabIndex = 1;
            this.txtRolUsuairo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRolUsuairo.TextMarginBottom = 0;
            this.txtRolUsuairo.TextMarginLeft = 3;
            this.txtRolUsuairo.TextMarginTop = 1;
            this.txtRolUsuairo.TextPlaceholder = "Rol";
            this.txtRolUsuairo.UseSystemPasswordChar = false;
            this.txtRolUsuairo.WordWrap = true;
            // 
            // lblCaracteristicasUsuario
            // 
            this.lblCaracteristicasUsuario.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblCaracteristicasUsuario.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCaracteristicasUsuario.Location = new System.Drawing.Point(0, 0);
            this.lblCaracteristicasUsuario.Name = "lblCaracteristicasUsuario";
            this.lblCaracteristicasUsuario.Size = new System.Drawing.Size(753, 41);
            this.lblCaracteristicasUsuario.TabIndex = 0;
            this.lblCaracteristicasUsuario.Text = "Características del usuario";
            this.lblCaracteristicasUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // txtConfirmarContraseña
            // 
            this.txtConfirmarContraseña.AcceptsReturn = false;
            this.txtConfirmarContraseña.AcceptsTab = false;
            this.txtConfirmarContraseña.AnimationSpeed = 200;
            this.txtConfirmarContraseña.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtConfirmarContraseña.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtConfirmarContraseña.AutoSizeHeight = true;
            this.txtConfirmarContraseña.BackColor = System.Drawing.Color.Transparent;
            this.txtConfirmarContraseña.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtConfirmarContraseña.BackgroundImage")));
            this.txtConfirmarContraseña.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtConfirmarContraseña.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtConfirmarContraseña.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtConfirmarContraseña.BorderColorIdle = System.Drawing.Color.White;
            this.txtConfirmarContraseña.BorderRadius = 15;
            this.txtConfirmarContraseña.BorderThickness = 1;
            this.txtConfirmarContraseña.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtConfirmarContraseña.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmarContraseña.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtConfirmarContraseña.DefaultText = "";
            this.txtConfirmarContraseña.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtConfirmarContraseña.FillColor = System.Drawing.Color.White;
            this.txtConfirmarContraseña.ForeColor = System.Drawing.Color.Black;
            this.txtConfirmarContraseña.HideSelection = true;
            this.txtConfirmarContraseña.IconLeft = global::Artemis.Properties.Resources._lock;
            this.txtConfirmarContraseña.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmarContraseña.IconPadding = 10;
            this.txtConfirmarContraseña.IconRight = null;
            this.txtConfirmarContraseña.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtConfirmarContraseña.Lines = new string[0];
            this.txtConfirmarContraseña.Location = new System.Drawing.Point(379, 3);
            this.txtConfirmarContraseña.MaxLength = 32767;
            this.txtConfirmarContraseña.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtConfirmarContraseña.Modified = false;
            this.txtConfirmarContraseña.Multiline = false;
            this.txtConfirmarContraseña.Name = "txtConfirmarContraseña";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties5.FillColor = System.Drawing.Color.White;
            stateProperties5.ForeColor = System.Drawing.Color.Black;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtConfirmarContraseña.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtConfirmarContraseña.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties7.FillColor = System.Drawing.Color.White;
            stateProperties7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(184)))), ((int)(((byte)(114)))));
            this.txtConfirmarContraseña.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtConfirmarContraseña.OnIdleState = stateProperties8;
            this.txtConfirmarContraseña.Padding = new System.Windows.Forms.Padding(3);
            this.txtConfirmarContraseña.PasswordChar = '\0';
            this.txtConfirmarContraseña.PlaceholderForeColor = System.Drawing.Color.Black;
            this.txtConfirmarContraseña.PlaceholderText = "Confirmar contraseña";
            this.txtConfirmarContraseña.ReadOnly = false;
            this.txtConfirmarContraseña.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtConfirmarContraseña.SelectedText = "";
            this.txtConfirmarContraseña.SelectionLength = 0;
            this.txtConfirmarContraseña.SelectionStart = 0;
            this.txtConfirmarContraseña.ShortcutsEnabled = true;
            this.txtConfirmarContraseña.Size = new System.Drawing.Size(351, 38);
            this.txtConfirmarContraseña.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtConfirmarContraseña.TabIndex = 1;
            this.txtConfirmarContraseña.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtConfirmarContraseña.TextMarginBottom = 0;
            this.txtConfirmarContraseña.TextMarginLeft = 8;
            this.txtConfirmarContraseña.TextMarginTop = 1;
            this.txtConfirmarContraseña.TextPlaceholder = "Confirmar contraseña";
            this.txtConfirmarContraseña.UseSystemPasswordChar = false;
            this.txtConfirmarContraseña.WordWrap = true;
            // 
            // EditorUsuario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(770, 422);
            this.Controls.Add(this.pnlPrincipal);
            this.Controls.Add(this.pnlBotones);
            this.Controls.Add(this.lblTitulo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "EditorUsuario";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Editor Usuario";
            this.pnlBotones.ResumeLayout(false);
            this.pnlPrincipal.ResumeLayout(false);
            this.pnlContraseña.ResumeLayout(false);
            this.pnlEmpleados.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvEmpleados)).EndInit();
            this.pnlCaracteristicasCliente.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse formBorderStyle;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.FlowLayoutPanel pnlBotones;
        private System.Windows.Forms.Panel pnlPrincipal;
        private System.Windows.Forms.TableLayoutPanel pnlCaracteristicasCliente;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombreUsuario;
        private System.Windows.Forms.Label lblCaracteristicasUsuario;
        private System.Windows.Forms.TableLayoutPanel pnlEmpleados;
        private Bunifu.UI.WinForms.BunifuTextBox txtBuscarEmpleado;
        private System.Windows.Forms.Label lblAsignacionUsuario;
        private Bunifu.UI.WinForms.BunifuTextBox txtRolUsuairo;
        private System.Windows.Forms.DataGridView dgvEmpleados;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGuardar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLimpiar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancelar;
        private System.Windows.Forms.TableLayoutPanel pnlContraseña;
        private Bunifu.UI.WinForms.BunifuTextBox txtContraseña;
        private System.Windows.Forms.Label lblContraseña;
        private Bunifu.UI.WinForms.BunifuTextBox txtConfirmarContraseña;
    }
}